package Views;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import Controllers.Administracion_json;

public class Formulario_Empleo_Informacion extends javax.swing.JFrame {

    public Connection connection;
    String sexo = "", domicilio = "", modo = "";
     
    public Formulario_Empleo_Informacion(Connection connection) {
        initComponents();   
        
        this.connection = connection;
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        
        cargarPaises();
        carga_edades();
    }

    // Metodo para cargar todas las edades en los boxs de la vista.
    private void carga_edades() {
		
	for(int counter = 18; counter <= 60; counter++){
	    jComboEdadmin.addItem(counter);
            jComboEdadmax.addItem(counter);
        }
    }
    
    // Metodo para cargar todos los paises provenientes de la base de datos a los boxes de la vista.
    private void cargarPaises(){
    
            try{
                ResultSet rs = connection.prepareStatement("SELECT * FROM paises").executeQuery();
                
                while(rs.next())
                    jComboNacionalidad.addItem(rs.getString(3));
                
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jComboNacionalidad.setSelectedIndex(231);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupSexo = new javax.swing.ButtonGroup();
        GroupModalidad = new javax.swing.ButtonGroup();
        GroupDomicilio = new javax.swing.ButtonGroup();
        jPIngreso = new javax.swing.JPanel();
        jPPage1 = new javax.swing.JPanel();
        jInfPersonal = new javax.swing.JLabel();
        jPDATOS = new javax.swing.JPanel();
        jTextEmpresa = new javax.swing.JTextField();
        jSepEmpresa = new javax.swing.JSeparator();
        jTextContEmpresa = new javax.swing.JTextField();
        jSepContEmpresa = new javax.swing.JSeparator();
        jNacionalidad = new javax.swing.JPanel();
        jComboNacionalidad = new javax.swing.JComboBox<>();
        jPanelContacto = new javax.swing.JPanel();
        jTextCorreo = new javax.swing.JTextField();
        jSepCorreo = new javax.swing.JSeparator();
        jPanelDescripcion = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        descripcionTrabajo = new javax.swing.JTextArea();
        jPanelPostulante = new javax.swing.JPanel();
        jSexo = new javax.swing.JPanel();
        jPanelFemen = new javax.swing.JPanel();
        jRadioFemen = new javax.swing.JRadioButton();
        jPanelMan = new javax.swing.JPanel();
        jRadioMasc = new javax.swing.JRadioButton();
        jPanelAmbosSex = new javax.swing.JPanel();
        jRadioAmbos = new javax.swing.JRadioButton();
        jPanelEdad = new javax.swing.JPanel();
        jComboEdadmin = new javax.swing.JComboBox<>();
        jComboEdadmax = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanelEmpleo = new javax.swing.JPanel();
        jPanelModalidad = new javax.swing.JPanel();
        jPanelPresencial = new javax.swing.JPanel();
        modoPresencial = new javax.swing.JCheckBox();
        jPanelRemoto = new javax.swing.JPanel();
        modoRemoto = new javax.swing.JCheckBox();
        jPanelAmbasMod = new javax.swing.JPanel();
        modoAmbos = new javax.swing.JCheckBox();
        jPanelDomicilio = new javax.swing.JPanel();
        jPanelNacional = new javax.swing.JPanel();
        domNacional = new javax.swing.JCheckBox();
        jPanelInter = new javax.swing.JPanel();
        domInternacional = new javax.swing.JCheckBox();
        jPanelAmbosDom = new javax.swing.JPanel();
        ambosDomicilio = new javax.swing.JCheckBox();
        jCancel = new javax.swing.JButton();
        jNext = new javax.swing.JButton();
        jBackGround = new javax.swing.JLabel();
        jPanelSuperior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelLateral = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPIngreso.setBackground(new java.awt.Color(3, 153, 129));
        jPIngreso.setPreferredSize(new java.awt.Dimension(950, 670));
        jPIngreso.setLayout(null);

        jPPage1.setBackground(new java.awt.Color(255, 255, 255));
        jPPage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPPage1.setFocusable(false);
        jPPage1.setMaximumSize(new java.awt.Dimension(950, 670));
        jPPage1.setMinimumSize(new java.awt.Dimension(950, 670));
        jPPage1.setOpaque(false);
        jPPage1.setPreferredSize(new java.awt.Dimension(950, 670));
        jPPage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInfPersonal.setFont(new java.awt.Font("Dosis", 1, 36)); // NOI18N
        jInfPersonal.setText("Oferta de empleo");
        jPPage1.add(jInfPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 60));

        jPDATOS.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPRESA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPDATOS.setOpaque(false);

        jTextEmpresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextEmpresa.setForeground(new java.awt.Color(0, 153, 204));
        jTextEmpresa.setText("EMPRESA");
        jTextEmpresa.setBorder(null);
        jTextEmpresa.setOpaque(false);
        jTextEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEmpresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEmpresaFocusLost(evt);
            }
        });
        jTextEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmpresaActionPerformed(evt);
            }
        });
        jTextEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextEmpresaKeyTyped(evt);
            }
        });

        jTextContEmpresa.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextContEmpresa.setForeground(new java.awt.Color(0, 153, 204));
        jTextContEmpresa.setText("CÓDIGO EMPRESA");
        jTextContEmpresa.setBorder(null);
        jTextContEmpresa.setOpaque(false);
        jTextContEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextContEmpresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextContEmpresaFocusLost(evt);
            }
        });
        jTextContEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContEmpresaActionPerformed(evt);
            }
        });
        jTextContEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextContEmpresaKeyTyped(evt);
            }
        });

        jNacionalidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ubicación", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jNacionalidad.setOpaque(false);

        jComboNacionalidad.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jComboNacionalidad.setForeground(new java.awt.Color(0, 153, 204));
        jComboNacionalidad.setOpaque(false);
        jComboNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNacionalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jNacionalidadLayout = new javax.swing.GroupLayout(jNacionalidad);
        jNacionalidad.setLayout(jNacionalidadLayout);
        jNacionalidadLayout.setHorizontalGroup(
            jNacionalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNacionalidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboNacionalidad, 0, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        jNacionalidadLayout.setVerticalGroup(
            jNacionalidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNacionalidadLayout.createSequentialGroup()
                .addComponent(jComboNacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "contacto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelContacto.setOpaque(false);

        jTextCorreo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTextCorreo.setForeground(new java.awt.Color(0, 153, 204));
        jTextCorreo.setText("CORREO");
        jTextCorreo.setBorder(null);
        jTextCorreo.setOpaque(false);
        jTextCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextCorreoFocusLost(evt);
            }
        });
        jTextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCorreoActionPerformed(evt);
            }
        });
        jTextCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCorreoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelContactoLayout = new javax.swing.GroupLayout(jPanelContacto);
        jPanelContacto.setLayout(jPanelContactoLayout);
        jPanelContactoLayout.setHorizontalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
            .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelContactoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(jSepCorreo))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelContactoLayout.setVerticalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelContactoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jSepCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPDATOSLayout = new javax.swing.GroupLayout(jPDATOS);
        jPDATOS.setLayout(jPDATOSLayout);
        jPDATOSLayout.setHorizontalGroup(
            jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDATOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEmpresa)
                    .addComponent(jSepEmpresa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSepContEmpresa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextContEmpresa)
                    .addComponent(jNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPDATOSLayout.setVerticalGroup(
            jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDATOSLayout.createSequentialGroup()
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextContEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSepEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSepContEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jNacionalidad.getAccessibleContext().setAccessibleName("NACIONALIDAD");

        jPPage1.add(jPDATOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 390, 160));

        jPanelDescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "descipción general del empleo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelDescripcion.setOpaque(false);
        jPanelDescripcion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        descripcionTrabajo.setColumns(20);
        descripcionTrabajo.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        descripcionTrabajo.setRows(5);
        descripcionTrabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionTrabajoKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(descripcionTrabajo);

        jPanelDescripcion.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 620, 110));

        jPPage1.add(jPanelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 680, 150));

        jPanelPostulante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "POSTULANTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelPostulante.setOpaque(false);
        jPanelPostulante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "sexo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jSexo.setForeground(new java.awt.Color(0, 153, 204));
        jSexo.setOpaque(false);
        jSexo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFemen.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanelFemen.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanelFemen.setOpaque(false);

        jRadioFemen.setBackground(new java.awt.Color(244, 244, 244));
        GroupSexo.add(jRadioFemen);
        jRadioFemen.setForeground(new java.awt.Color(0, 204, 204));
        jRadioFemen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioFemen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioFemen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioFemen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_woman_50px_1.png"))); // NOI18N
        jRadioFemen.setMaximumSize(new java.awt.Dimension(50, 50));
        jRadioFemen.setMinimumSize(new java.awt.Dimension(50, 50));
        jRadioFemen.setOpaque(false);
        jRadioFemen.setPreferredSize(new java.awt.Dimension(50, 50));
        jRadioFemen.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_woman_50px.png"))); // NOI18N
        jRadioFemen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioFemenMouseMoved(evt);
            }
        });
        jRadioFemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioFemenMouseExited(evt);
            }
        });
        jRadioFemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFemenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFemenLayout = new javax.swing.GroupLayout(jPanelFemen);
        jPanelFemen.setLayout(jPanelFemenLayout);
        jPanelFemenLayout.setHorizontalGroup(
            jPanelFemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelFemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFemenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioFemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelFemenLayout.setVerticalGroup(
            jPanelFemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelFemenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFemenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioFemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jSexo.add(jPanelFemen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanelMan.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanelMan.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanelMan.setOpaque(false);

        jRadioMasc.setBackground(new java.awt.Color(244, 244, 244));
        GroupSexo.add(jRadioMasc);
        jRadioMasc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioMasc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioMasc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioMasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_man_50px_1.png"))); // NOI18N
        jRadioMasc.setMaximumSize(new java.awt.Dimension(50, 50));
        jRadioMasc.setMinimumSize(new java.awt.Dimension(50, 50));
        jRadioMasc.setOpaque(false);
        jRadioMasc.setPreferredSize(new java.awt.Dimension(50, 50));
        jRadioMasc.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_man_50px.png"))); // NOI18N
        jRadioMasc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioMascMouseMoved(evt);
            }
        });
        jRadioMasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioMascMouseExited(evt);
            }
        });
        jRadioMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMascActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelManLayout = new javax.swing.GroupLayout(jPanelMan);
        jPanelMan.setLayout(jPanelManLayout);
        jPanelManLayout.setHorizontalGroup(
            jPanelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelManLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelManLayout.setVerticalGroup(
            jPanelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelManLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelManLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioMasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jSexo.add(jPanelMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanelAmbosSex.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanelAmbosSex.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanelAmbosSex.setOpaque(false);
        jPanelAmbosSex.setPreferredSize(new java.awt.Dimension(50, 50));

        jRadioAmbos.setBackground(new java.awt.Color(244, 244, 244));
        GroupSexo.add(jRadioAmbos);
        jRadioAmbos.setAlignmentY(0.0F);
        jRadioAmbos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioAmbos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioAmbos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioAmbos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_couple_50px_.png"))); // NOI18N
        jRadioAmbos.setMaximumSize(new java.awt.Dimension(50, 50));
        jRadioAmbos.setMinimumSize(new java.awt.Dimension(50, 50));
        jRadioAmbos.setOpaque(false);
        jRadioAmbos.setPreferredSize(new java.awt.Dimension(50, 50));
        jRadioAmbos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_couple_50px-1.png"))); // NOI18N
        jRadioAmbos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioAmbosMouseMoved(evt);
            }
        });
        jRadioAmbos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioAmbosMouseExited(evt);
            }
        });
        jRadioAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAmbosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAmbosSexLayout = new javax.swing.GroupLayout(jPanelAmbosSex);
        jPanelAmbosSex.setLayout(jPanelAmbosSexLayout);
        jPanelAmbosSexLayout.setHorizontalGroup(
            jPanelAmbosSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelAmbosSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAmbosSexLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelAmbosSexLayout.setVerticalGroup(
            jPanelAmbosSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanelAmbosSexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAmbosSexLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jRadioAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jSexo.add(jPanelAmbosSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jPanelPostulante.add(jSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 80));

        jPanelEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "edad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelEdad.setOpaque(false);
        jPanelEdad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboEdadmin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboEdadmin.setForeground(new java.awt.Color(0, 153, 204));
        jComboEdadmin.setOpaque(false);
        jComboEdadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEdadminActionPerformed(evt);
            }
        });
        jPanelEdad.add(jComboEdadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, 30));

        jComboEdadmax.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboEdadmax.setForeground(new java.awt.Color(0, 153, 204));
        jComboEdadmax.setOpaque(false);
        jComboEdadmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEdadmaxActionPerformed(evt);
            }
        });
        jPanelEdad.add(jComboEdadmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, 30));

        jLabel3.setFont(new java.awt.Font("Dosis", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("-");
        jPanelEdad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 40, 30, 13));

        jPanelPostulante.add(jPanelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 160, 80));

        jPPage1.add(jPanelPostulante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 390, 110));

        jPanelEmpleo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPLEO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelEmpleo.setOpaque(false);

        jPanelModalidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "modalidad", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelModalidad.setMinimumSize(new java.awt.Dimension(120, 210));
        jPanelModalidad.setOpaque(false);
        jPanelModalidad.setPreferredSize(new java.awt.Dimension(120, 210));
        jPanelModalidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPresencial.setMaximumSize(new java.awt.Dimension(80, 60));
        jPanelPresencial.setMinimumSize(new java.awt.Dimension(80, 60));
        jPanelPresencial.setOpaque(false);
        jPanelPresencial.setPreferredSize(new java.awt.Dimension(80, 60));

        GroupModalidad.add(modoPresencial);
        modoPresencial.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        modoPresencial.setForeground(new java.awt.Color(0, 153, 204));
        modoPresencial.setText("Presencial");
        modoPresencial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modoPresencial.setFocusable(false);
        modoPresencial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modoPresencial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoPresencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/work (1).png"))); // NOI18N
        modoPresencial.setMaximumSize(new java.awt.Dimension(70, 60));
        modoPresencial.setMinimumSize(new java.awt.Dimension(70, 60));
        modoPresencial.setOpaque(false);
        modoPresencial.setPreferredSize(new java.awt.Dimension(80, 60));
        modoPresencial.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/work (2).png"))); // NOI18N
        modoPresencial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoPresencial.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modoPresencialMouseMoved(evt);
            }
        });
        modoPresencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modoPresencialMouseExited(evt);
            }
        });
        modoPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoPresencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPresencialLayout = new javax.swing.GroupLayout(jPanelPresencial);
        jPanelPresencial.setLayout(jPanelPresencialLayout);
        jPanelPresencialLayout.setHorizontalGroup(
            jPanelPresencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelPresencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPresencialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modoPresencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelPresencialLayout.setVerticalGroup(
            jPanelPresencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelPresencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelPresencialLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modoPresencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelModalidad.add(jPanelPresencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanelRemoto.setMaximumSize(new java.awt.Dimension(80, 60));
        jPanelRemoto.setMinimumSize(new java.awt.Dimension(80, 60));
        jPanelRemoto.setOpaque(false);

        GroupModalidad.add(modoRemoto);
        modoRemoto.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        modoRemoto.setForeground(new java.awt.Color(0, 153, 204));
        modoRemoto.setText("Remoto");
        modoRemoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modoRemoto.setFocusable(false);
        modoRemoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modoRemoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoRemoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desk.png"))); // NOI18N
        modoRemoto.setMaximumSize(new java.awt.Dimension(70, 60));
        modoRemoto.setMinimumSize(new java.awt.Dimension(70, 60));
        modoRemoto.setOpaque(false);
        modoRemoto.setPreferredSize(new java.awt.Dimension(80, 60));
        modoRemoto.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desk (1).png"))); // NOI18N
        modoRemoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoRemoto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modoRemotoMouseMoved(evt);
            }
        });
        modoRemoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modoRemotoMouseExited(evt);
            }
        });
        modoRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoRemotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRemotoLayout = new javax.swing.GroupLayout(jPanelRemoto);
        jPanelRemoto.setLayout(jPanelRemotoLayout);
        jPanelRemotoLayout.setHorizontalGroup(
            jPanelRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRemotoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modoRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelRemotoLayout.setVerticalGroup(
            jPanelRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelRemotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRemotoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modoRemoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelModalidad.add(jPanelRemoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanelAmbasMod.setMaximumSize(new java.awt.Dimension(80, 60));
        jPanelAmbasMod.setMinimumSize(new java.awt.Dimension(80, 60));
        jPanelAmbasMod.setOpaque(false);

        GroupModalidad.add(modoAmbos);
        modoAmbos.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        modoAmbos.setForeground(new java.awt.Color(0, 153, 204));
        modoAmbos.setText("Ámbos");
        modoAmbos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modoAmbos.setFocusable(false);
        modoAmbos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modoAmbos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoAmbos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/work both.png"))); // NOI18N
        modoAmbos.setMaximumSize(new java.awt.Dimension(80, 60));
        modoAmbos.setMinimumSize(new java.awt.Dimension(80, 60));
        modoAmbos.setOpaque(false);
        modoAmbos.setPreferredSize(new java.awt.Dimension(80, 60));
        modoAmbos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/work BOTH(2).png"))); // NOI18N
        modoAmbos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoAmbos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modoAmbosMouseMoved(evt);
            }
        });
        modoAmbos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modoAmbosMouseExited(evt);
            }
        });
        modoAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoAmbosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAmbasModLayout = new javax.swing.GroupLayout(jPanelAmbasMod);
        jPanelAmbasMod.setLayout(jPanelAmbasModLayout);
        jPanelAmbasModLayout.setHorizontalGroup(
            jPanelAmbasModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelAmbasModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAmbasModLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modoAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelAmbasModLayout.setVerticalGroup(
            jPanelAmbasModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelAmbasModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAmbasModLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(modoAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelModalidad.add(jPanelAmbasMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanelDomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "domicilio", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelDomicilio.setMinimumSize(new java.awt.Dimension(120, 210));
        jPanelDomicilio.setOpaque(false);
        jPanelDomicilio.setPreferredSize(new java.awt.Dimension(120, 210));
        jPanelDomicilio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNacional.setMaximumSize(new java.awt.Dimension(80, 60));
        jPanelNacional.setMinimumSize(new java.awt.Dimension(80, 60));
        jPanelNacional.setOpaque(false);

        GroupDomicilio.add(domNacional);
        domNacional.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        domNacional.setForeground(new java.awt.Color(0, 153, 204));
        domNacional.setText("Nacional");
        domNacional.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        domNacional.setFocusable(false);
        domNacional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        domNacional.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        domNacional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_country_32px.png"))); // NOI18N
        domNacional.setMaximumSize(new java.awt.Dimension(80, 60));
        domNacional.setMinimumSize(new java.awt.Dimension(80, 60));
        domNacional.setOpaque(false);
        domNacional.setPreferredSize(new java.awt.Dimension(80, 60));
        domNacional.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_country_32px_1.png"))); // NOI18N
        domNacional.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        domNacional.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                domNacionalMouseMoved(evt);
            }
        });
        domNacional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                domNacionalMouseExited(evt);
            }
        });
        domNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domNacionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNacionalLayout = new javax.swing.GroupLayout(jPanelNacional);
        jPanelNacional.setLayout(jPanelNacionalLayout);
        jPanelNacionalLayout.setHorizontalGroup(
            jPanelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelNacionalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(domNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelNacionalLayout.setVerticalGroup(
            jPanelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelNacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelNacionalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(domNacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelDomicilio.add(jPanelNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanelInter.setMaximumSize(new java.awt.Dimension(80, 60));
        jPanelInter.setMinimumSize(new java.awt.Dimension(80, 60));
        jPanelInter.setOpaque(false);

        GroupDomicilio.add(domInternacional);
        domInternacional.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        domInternacional.setForeground(new java.awt.Color(0, 153, 204));
        domInternacional.setText("Internacional");
        domInternacional.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        domInternacional.setFocusable(false);
        domInternacional.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        domInternacional.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        domInternacional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_worldwide_location_32px_1.png"))); // NOI18N
        domInternacional.setMaximumSize(new java.awt.Dimension(80, 60));
        domInternacional.setMinimumSize(new java.awt.Dimension(80, 60));
        domInternacional.setOpaque(false);
        domInternacional.setPreferredSize(new java.awt.Dimension(80, 60));
        domInternacional.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_worldwide_location_32px.png"))); // NOI18N
        domInternacional.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        domInternacional.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                domInternacionalMouseMoved(evt);
            }
        });
        domInternacional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                domInternacionalMouseExited(evt);
            }
        });
        domInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domInternacionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInterLayout = new javax.swing.GroupLayout(jPanelInter);
        jPanelInter.setLayout(jPanelInterLayout);
        jPanelInterLayout.setHorizontalGroup(
            jPanelInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(domInternacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelInterLayout.setVerticalGroup(
            jPanelInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(domInternacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelDomicilio.add(jPanelInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanelAmbosDom.setMaximumSize(new java.awt.Dimension(80, 60));
        jPanelAmbosDom.setMinimumSize(new java.awt.Dimension(80, 60));
        jPanelAmbosDom.setOpaque(false);

        GroupDomicilio.add(ambosDomicilio);
        ambosDomicilio.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        ambosDomicilio.setForeground(new java.awt.Color(0, 153, 204));
        ambosDomicilio.setText("Ámbos");
        ambosDomicilio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ambosDomicilio.setFocusable(false);
        ambosDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ambosDomicilio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ambosDomicilio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_country_32px - copia.png"))); // NOI18N
        ambosDomicilio.setMaximumSize(new java.awt.Dimension(80, 60));
        ambosDomicilio.setMinimumSize(new java.awt.Dimension(80, 60));
        ambosDomicilio.setOpaque(false);
        ambosDomicilio.setPreferredSize(new java.awt.Dimension(80, 60));
        ambosDomicilio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_country_32px_1 - copia.png"))); // NOI18N
        ambosDomicilio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ambosDomicilio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ambosDomicilioMouseMoved(evt);
            }
        });
        ambosDomicilio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ambosDomicilioMouseExited(evt);
            }
        });
        ambosDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambosDomicilioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAmbosDomLayout = new javax.swing.GroupLayout(jPanelAmbosDom);
        jPanelAmbosDom.setLayout(jPanelAmbosDomLayout);
        jPanelAmbosDomLayout.setHorizontalGroup(
            jPanelAmbosDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelAmbosDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAmbosDomLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ambosDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelAmbosDomLayout.setVerticalGroup(
            jPanelAmbosDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelAmbosDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAmbosDomLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ambosDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelDomicilio.add(jPanelAmbosDom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        javax.swing.GroupLayout jPanelEmpleoLayout = new javax.swing.GroupLayout(jPanelEmpleo);
        jPanelEmpleo.setLayout(jPanelEmpleoLayout);
        jPanelEmpleoLayout.setHorizontalGroup(
            jPanelEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelEmpleoLayout.setVerticalGroup(
            jPanelEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleoLayout.createSequentialGroup()
                .addGroup(jPanelEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelModalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPPage1.add(jPanelEmpleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 280, 270));

        jCancel.setBackground(new java.awt.Color(0, 51, 51));
        jCancel.setForeground(new java.awt.Color(0, 51, 51));
        jCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px.png"))); // NOI18N
        jCancel.setBorderPainted(false);
        jCancel.setContentAreaFilled(false);
        jCancel.setPreferredSize(new java.awt.Dimension(40, 40));
        jCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jPPage1.add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 60, 60));

        jNext.setBackground(new java.awt.Color(0, 51, 51));
        jNext.setForeground(new java.awt.Color(0, 51, 51));
        jNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_2.png"))); // NOI18N
        jNext.setBorderPainted(false);
        jNext.setContentAreaFilled(false);
        jNext.setPreferredSize(new java.awt.Dimension(40, 40));
        jNext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_3.png"))); // NOI18N
        jNext.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_3.png"))); // NOI18N
        jNext.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_3.png"))); // NOI18N
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        jPPage1.add(jNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 60, 60));

        jPIngreso.add(jPPage1);
        jPPage1.setBounds(0, 0, 950, 670);

        jBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg2.gif"))); // NOI18N
        jPIngreso.add(jBackGround);
        jBackGround.setBounds(0, 0, 950, 670);

        getContentPane().add(jPIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 950, 670));

        jPanelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(950, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(894, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 30));

        jPanelLateral.setBackground(new java.awt.Color(0, 51, 51));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(50, 700));

        jButtonClose.setBackground(new java.awt.Color(0, 51, 51));
        jButtonClose.setForeground(new java.awt.Color(0, 51, 51));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px.png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px_1.png"))); // NOI18N
        jButtonClose.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px_1.png"))); // NOI18N
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px_1.png"))); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap(609, Short.MAX_VALUE)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        Dialogs d = new Dialogs(2);
        d.setVisible(true);
    
        if(d.getState() == true)
        {   Menu_Principal mp = new Menu_Principal(connection);
            mp.setVisible(true);
	    dispose();
        }
    }//GEN-LAST:event_jCancelActionPerformed

    // Metodo de evento cuando se oprime el boton siguiente de la interfaz.
    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        Dialogs d; 
        // Se verifica si el rango de edades fue introducido correctamente.
        if(jComboEdadmin.getItemAt(jComboEdadmin.getSelectedIndex()) > jComboEdadmax.getItemAt(jComboEdadmax.getSelectedIndex())){
            {d = new Dialogs(8); //Inconsistencia en rango de edad
             d.setVisible(true);}
            return;
        }
            
        if(jTextEmpresa.getText().equals("") || jTextContEmpresa.getText().equals("") || !(jRadioMasc.isSelected() || jRadioFemen.isSelected() || jRadioAmbos.isSelected()) || !(domNacional.isSelected() || domInternacional.isSelected() || ambosDomicilio.isSelected()) || !(modoPresencial.isSelected() || modoRemoto.isSelected() || modoAmbos.isSelected()) || jTextCorreo.getText().equals("") || descripcionTrabajo.getText().equals("")){
            {d = new Dialogs(6); //FORMULARIO INCOMPLETO
             d.setVisible(true);}
            return;
        }
        
        if(agregarOfertaEmpleoDatabase(sexo, domicilio, modo, jTextContEmpresa.getText())){
            Formulario_Empleo_Conocimientos fec = new Formulario_Empleo_Conocimientos(Integer.parseInt(jTextContEmpresa.getText()), connection);
            fec.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jNextActionPerformed

    private void jTextEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmpresaFocusGained
        if(jTextEmpresa.getText().equals("EMPRESA"))
            jTextEmpresa.setText("");
    }//GEN-LAST:event_jTextEmpresaFocusGained

    private void jTextEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEmpresaFocusLost
        if(jTextEmpresa.getText().equals(""))
            jTextEmpresa.setText("EMPRESA");
    }//GEN-LAST:event_jTextEmpresaFocusLost

    private void jTextEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmpresaActionPerformed

    private void jTextEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEmpresaKeyTyped
        
        int character = (int)evt.getKeyChar();
        
        if(character < 65 || (character > 90 && character < 97) || character > 122 || (jTextEmpresa.getText().length() + 1 > 50) ){
            evt.consume();
            return;
        }
        
        char c=evt.getKeyChar();
        String s="";

        if(evt.getSource().equals(jTextEmpresa)) {
            if(Character.isDigit(c)||Character.isWhitespace(c)) {
                getToolkit().beep();
                evt.consume();
                s=jTextEmpresa.getText();
                jTextEmpresa.setText(null);
                jTextEmpresa.setText(s);
            }
        }
    }//GEN-LAST:event_jTextEmpresaKeyTyped

    private void jTextContEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextContEmpresaFocusGained
        if(jTextContEmpresa.getText().equals("CÓDIGO EMPRESA"))
            jTextContEmpresa.setText("");
    }//GEN-LAST:event_jTextContEmpresaFocusGained

    private void jTextContEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextContEmpresaFocusLost
        if(jTextContEmpresa.getText().equals(""))
            jTextContEmpresa.setText("CÓDIGO EMPRESA");
    }//GEN-LAST:event_jTextContEmpresaFocusLost

    private void jTextContEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContEmpresaActionPerformed

    private void jTextContEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContEmpresaKeyTyped
        
        int character = (int)evt.getKeyChar();
        
        if(character < 48 || character > 57 || (jTextContEmpresa.getText().length() + 1 > 10) ){
            evt.consume();
            return;
        }
        
        char c=evt.getKeyChar();
            String s="";
            
              if(evt.getSource().equals(jTextContEmpresa)){
                     if(Character.isLetter(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextContEmpresa.getText();
                        jTextContEmpresa.setText(null);
                        jTextContEmpresa.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextContEmpresaKeyTyped

    private void jRadioFemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFemenActionPerformed
        sexo= "Femenino";
    }//GEN-LAST:event_jRadioFemenActionPerformed

    private void jRadioMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMascActionPerformed
       sexo = "Masculino";
    }//GEN-LAST:event_jRadioMascActionPerformed

    private void jRadioAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAmbosActionPerformed
       sexo = "Ambos";
    }//GEN-LAST:event_jRadioAmbosActionPerformed

    private void jComboEdadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEdadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEdadminActionPerformed

    private void jComboEdadmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEdadmaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEdadmaxActionPerformed

    private void domNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domNacionalActionPerformed
        domicilio = "Nacional";
        
        domInternacional.setSelected(false);
        ambosDomicilio.setSelected(false);
    }//GEN-LAST:event_domNacionalActionPerformed

    private void domInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domInternacionalActionPerformed
        domicilio = "Internacional";
        
        domNacional.setSelected(false);
        ambosDomicilio.setSelected(false);
    }//GEN-LAST:event_domInternacionalActionPerformed

    private void ambosDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambosDomicilioActionPerformed
        domicilio = "Ambos";
        
        domNacional.setSelected(false);
        domInternacional.setSelected(false);
    }//GEN-LAST:event_ambosDomicilioActionPerformed

    private void modoPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoPresencialActionPerformed
        modo = "Presencial";
        
        if(!modoPresencial.isSelected()){
            domInternacional.setEnabled(true);
            ambosDomicilio.setEnabled(true);
        }
        else{
            domInternacional.setEnabled(false);
            ambosDomicilio.setEnabled(false);
        }

        modoRemoto.setSelected(false);
        modoAmbos.setSelected(false);
    }//GEN-LAST:event_modoPresencialActionPerformed

    private void modoRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoRemotoActionPerformed
        modo = "Remoto";
        
        domInternacional.setEnabled(true);
        ambosDomicilio.setEnabled(true);

        modoPresencial.setSelected(false);
        modoAmbos.setSelected(false);
    }//GEN-LAST:event_modoRemotoActionPerformed

    private void modoAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoAmbosActionPerformed
        modo = "Ambos";
        
        domInternacional.setEnabled(true);
        ambosDomicilio.setEnabled(true);

        modoPresencial.setSelected(false);
        modoRemoto.setSelected(false);
    }//GEN-LAST:event_modoAmbosActionPerformed

    private void jComboNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboNacionalidadActionPerformed

    private void jTextCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCorreoFocusGained
        if(jTextCorreo.getText().equals("CORREO"))
            jTextCorreo.setText("");
    }//GEN-LAST:event_jTextCorreoFocusGained

    private void jTextCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCorreoFocusLost
        if(jTextCorreo.getText().equals(""))
            jTextCorreo.setText("CORREO");
    }//GEN-LAST:event_jTextCorreoFocusLost

    private void jTextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCorreoActionPerformed

    private void jTextCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCorreoKeyTyped
        
        if(jTextCorreo.getText().length() + 1 > 60)
            evt.consume();
        
        char c=evt.getKeyChar();
        String s="";

        if(evt.getSource().equals(jTextCorreo)) {
            if(Character.isWhitespace(c)) {
                getToolkit().beep();
                evt.consume();
                s=jTextCorreo.getText();
                jTextCorreo.setText(null);
                jTextCorreo.setText(s);
            }
        }
    }//GEN-LAST:event_jTextCorreoKeyTyped

    private void jRadioFemenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioFemenMouseMoved
       jPanelFemen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jRadioFemenMouseMoved

    private void jRadioFemenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioFemenMouseExited
        jPanelFemen.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jRadioFemenMouseExited

    private void jRadioMascMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioMascMouseMoved
        jPanelMan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jRadioMascMouseMoved

    private void jRadioMascMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioMascMouseExited
        jPanelMan.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jRadioMascMouseExited

    private void jRadioAmbosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioAmbosMouseMoved
        jPanelAmbosSex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jRadioAmbosMouseMoved

    private void jRadioAmbosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioAmbosMouseExited
         jPanelAmbosSex.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jRadioAmbosMouseExited

    private void modoPresencialMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoPresencialMouseMoved
        jPanelPresencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_modoPresencialMouseMoved

    private void modoPresencialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoPresencialMouseExited
        jPanelPresencial.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_modoPresencialMouseExited

    private void modoRemotoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoRemotoMouseMoved
        jPanelRemoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_modoRemotoMouseMoved

    private void modoRemotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoRemotoMouseExited
        jPanelRemoto.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_modoRemotoMouseExited

    private void modoAmbosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoAmbosMouseMoved
        jPanelAmbasMod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_modoAmbosMouseMoved

    private void modoAmbosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modoAmbosMouseExited
        jPanelAmbasMod.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_modoAmbosMouseExited

    private void ambosDomicilioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ambosDomicilioMouseMoved
        jPanelAmbosDom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_ambosDomicilioMouseMoved

    private void ambosDomicilioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ambosDomicilioMouseExited
        jPanelAmbosDom.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_ambosDomicilioMouseExited

    private void domNacionalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_domNacionalMouseMoved
        jPanelNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_domNacionalMouseMoved

    private void domNacionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_domNacionalMouseExited
        jPanelNacional.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_domNacionalMouseExited

    private void domInternacionalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_domInternacionalMouseMoved
        jPanelInter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_domInternacionalMouseMoved

    private void domInternacionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_domInternacionalMouseExited
        jPanelInter.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_domInternacionalMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setState(Formulario_Postulante_Info_Personal.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        Dialogs d = new Dialogs(1);
        d.setVisible(true);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void descripcionTrabajoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionTrabajoKeyTyped
        if(descripcionTrabajo.getText().length() + 1 > 300)
            evt.consume();
    }//GEN-LAST:event_descripcionTrabajoKeyTyped

    // Funcion para agregar un nuevo empleo a la base de datos.
    public boolean agregarOfertaEmpleoDatabase(String sexo, String domicilio, String modo, String codContrato){
        Dialogs d;
         try {
                PreparedStatement ps = connection.prepareStatement("INSERT INTO `oferta_empleo` (`idoferta_empleo`, `empresa` , `codcontrato`, `sexo`, `edadmin`, `edadmax`, `domicilio`, `modo`, `nacionalidad`, `descripcion`, `correo`) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                
                ps.setString(1, jTextEmpresa.getText());
                ps.setInt(2, Integer.parseInt(codContrato));
                ps.setString(3, sexo);
                ps.setInt(4, Integer.parseInt(jComboEdadmin.getSelectedItem().toString()));
                ps.setInt(5, Integer.parseInt(jComboEdadmax.getSelectedItem().toString()));
                ps.setString(6, domicilio);
                ps.setString(7, modo);
                ps.setString(8, jComboNacionalidad.getSelectedItem().toString());
                ps.setString(9, descripcionTrabajo.getText());
                ps.setString(10, jTextCorreo.getText());
                
                 // Verificamos si el codigo de contrato introducido ya se encuentra registrado.
                ResultSet rs = connection.prepareStatement("SELECT * FROM oferta_empleo").executeQuery();
                
                while(rs.next())
                    if(rs.getInt(3) == Integer.parseInt(codContrato)){
                       d = new Dialogs(11);//EMPLEO YA REGISTRADO
                       d.setVisible(true); 
                        return false;
                    }
                
                ps.executeUpdate();
                d = new Dialogs(9);//Oferta agregada correctamente
                d.setVisible(true);
                
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
                d = new Dialogs(5);
                d.setVisible(true);//ERROR GENERAL
            }
         return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupDomicilio;
    private javax.swing.ButtonGroup GroupModalidad;
    private javax.swing.ButtonGroup GroupSexo;
    private javax.swing.JCheckBox ambosDomicilio;
    private javax.swing.JTextArea descripcionTrabajo;
    private javax.swing.JCheckBox domInternacional;
    private javax.swing.JCheckBox domNacional;
    private javax.swing.JLabel jBackGround;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jCancel;
    private javax.swing.JComboBox<Integer> jComboEdadmax;
    private javax.swing.JComboBox<Integer> jComboEdadmin;
    private javax.swing.JComboBox<String> jComboNacionalidad;
    private javax.swing.JLabel jInfPersonal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jNacionalidad;
    private javax.swing.JButton jNext;
    private javax.swing.JPanel jPDATOS;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPPage1;
    private javax.swing.JPanel jPanelAmbasMod;
    private javax.swing.JPanel jPanelAmbosDom;
    private javax.swing.JPanel jPanelAmbosSex;
    private javax.swing.JPanel jPanelContacto;
    private javax.swing.JPanel jPanelDescripcion;
    private javax.swing.JPanel jPanelDomicilio;
    private javax.swing.JPanel jPanelEdad;
    private javax.swing.JPanel jPanelEmpleo;
    private javax.swing.JPanel jPanelFemen;
    private javax.swing.JPanel jPanelInter;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelMan;
    private javax.swing.JPanel jPanelModalidad;
    private javax.swing.JPanel jPanelNacional;
    private javax.swing.JPanel jPanelPostulante;
    private javax.swing.JPanel jPanelPresencial;
    private javax.swing.JPanel jPanelRemoto;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JRadioButton jRadioAmbos;
    private javax.swing.JRadioButton jRadioFemen;
    private javax.swing.JRadioButton jRadioMasc;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSepContEmpresa;
    private javax.swing.JSeparator jSepCorreo;
    private javax.swing.JSeparator jSepEmpresa;
    private javax.swing.JPanel jSexo;
    private javax.swing.JTextField jTextContEmpresa;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextEmpresa;
    private javax.swing.JCheckBox modoAmbos;
    private javax.swing.JCheckBox modoPresencial;
    private javax.swing.JCheckBox modoRemoto;
    // End of variables declaration//GEN-END:variables
}