/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Postulante;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import Controllers.Administracion_json;

/**
 *
 * @author Jesus Gonzalez
 */
public class Formulario_Postulante_Conocimientos extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;
    
    
    private Menu_Principal mp;
    
    private int opc_titulo, opc_especialidad, id_postulante;
    private Postulante nuevo_postulante;
    
    Connection connection;
        
        
    public Formulario_Postulante_Conocimientos(Postulante np, Connection connection) {
        
        initComponents();  
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        
        nuevo_postulante = new Postulante();
        nuevo_postulante = np;
        
	this.connection = connection;
                
        this.id_postulante = getIdPostulanteDatabase(np.getCorreo());
                
        System.out.println(this.id_postulante);
       
         prueba_postulante();      
               
        nuevo_postulante = new Postulante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTitulo = new javax.swing.ButtonGroup();
        GroupEspecialidades = new javax.swing.ButtonGroup();
        jPConcTec = new javax.swing.JPanel();
        jPPage1 = new javax.swing.JPanel();
        jConocTecn = new javax.swing.JLabel();
        jPanelTitulo = new javax.swing.JPanel();
        jPanelBachiller = new javax.swing.JPanel();
        jButtonBachiller = new javax.swing.JRadioButton();
        jPanelLicenciado = new javax.swing.JPanel();
        jButtonLicenciado = new javax.swing.JRadioButton();
        jPanelIngeniero = new javax.swing.JPanel();
        jButtonIngeniero = new javax.swing.JRadioButton();
        jPanelTecnico = new javax.swing.JPanel();
        jButtonTecnico = new javax.swing.JRadioButton();
        jPanelMagister = new javax.swing.JPanel();
        jButtonMagister = new javax.swing.JRadioButton();
        jPanelDoctor = new javax.swing.JPanel();
        jButtonDoctor = new javax.swing.JRadioButton();
        jPanelEspecilidades = new javax.swing.JPanel();
        jPanelComp = new javax.swing.JPanel();
        jButtonComputacion = new javax.swing.JRadioButton();
        jPanelInformatica = new javax.swing.JPanel();
        jButtonInformatica = new javax.swing.JRadioButton();
        jPanelSistema = new javax.swing.JPanel();
        jButtonSistema = new javax.swing.JRadioButton();
        jTexComputacion = new javax.swing.JTextField();
        jTextInformatica = new javax.swing.JTextField();
        jTextSistema = new javax.swing.JTextField();
        jPanelHerramientas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelCuadroHerramientas = new javax.swing.JPanel();
        jButtonCertificaciones = new javax.swing.JButton();
        jComboBoxCertificaciones = new javax.swing.JComboBox<>();
        jButtonHerramientas = new javax.swing.JButton();
        jComboBoxHerramientas = new javax.swing.JComboBox<>();
        jButtonConocGenerales = new javax.swing.JButton();
        jComboBoxCGenerales = new javax.swing.JComboBox<>();
        jButtonExpLaborales = new javax.swing.JButton();
        jComboBoxExpsLaborales = new javax.swing.JComboBox<>();
        jButtonLenguajes = new javax.swing.JButton();
        jComboBoxLenguajes = new javax.swing.JComboBox<>();
        jCancel = new javax.swing.JButton();
        jNext = new javax.swing.JButton();
        jBackGround = new javax.swing.JLabel();
        jPanelSuperior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelLateral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPConcTec.setBackground(new java.awt.Color(3, 153, 129));
        jPConcTec.setPreferredSize(new java.awt.Dimension(950, 670));
        jPConcTec.setLayout(null);

        jPPage1.setBackground(new java.awt.Color(255, 255, 255));
        jPPage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPPage1.setOpaque(false);
        jPPage1.setPreferredSize(new java.awt.Dimension(950, 670));
        jPPage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jConocTecn.setFont(new java.awt.Font("Dosis", 1, 36)); // NOI18N
        jConocTecn.setText("CONOCIMIENTOS TÉCNICOS");
        jPPage1.add(jConocTecn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 60));

        jPanelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NIVEL ACADÉMICO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelTitulo.setOpaque(false);
        jPanelTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBachiller.setAlignmentX(0.0F);
        jPanelBachiller.setAlignmentY(0.0F);
        jPanelBachiller.setMaximumSize(new java.awt.Dimension(110, 80));
        jPanelBachiller.setMinimumSize(new java.awt.Dimension(110, 80));
        jPanelBachiller.setOpaque(false);
        jPanelBachiller.setPreferredSize(new java.awt.Dimension(110, 80));

        GroupTitulo.add(jButtonBachiller);
        jButtonBachiller.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jButtonBachiller.setForeground(new java.awt.Color(0, 153, 204));
        jButtonBachiller.setText("Bachiller");
        jButtonBachiller.setContentAreaFilled(false);
        jButtonBachiller.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonBachiller.setFocusPainted(false);
        jButtonBachiller.setFocusable(false);
        jButtonBachiller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonBachiller.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBachiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/programmer.png"))); // NOI18N
        jButtonBachiller.setMaximumSize(new java.awt.Dimension(110, 80));
        jButtonBachiller.setMinimumSize(new java.awt.Dimension(110, 80));
        jButtonBachiller.setPreferredSize(new java.awt.Dimension(110, 80));
        jButtonBachiller.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/application.png"))); // NOI18N
        jButtonBachiller.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBachiller.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonBachillerMouseMoved(evt);
            }
        });
        jButtonBachiller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBachillerMouseExited(evt);
            }
        });
        jButtonBachiller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBachillerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBachillerLayout = new javax.swing.GroupLayout(jPanelBachiller);
        jPanelBachiller.setLayout(jPanelBachillerLayout);
        jPanelBachillerLayout.setHorizontalGroup(
            jPanelBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBachillerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonBachiller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelBachillerLayout.setVerticalGroup(
            jPanelBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelBachillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBachillerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonBachiller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTitulo.add(jPanelBachiller, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanelLicenciado.setAlignmentX(0.0F);
        jPanelLicenciado.setAlignmentY(0.0F);
        jPanelLicenciado.setMaximumSize(new java.awt.Dimension(110, 80));
        jPanelLicenciado.setMinimumSize(new java.awt.Dimension(110, 80));
        jPanelLicenciado.setOpaque(false);

        GroupTitulo.add(jButtonLicenciado);
        jButtonLicenciado.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jButtonLicenciado.setForeground(new java.awt.Color(0, 153, 204));
        jButtonLicenciado.setText("Licenciado");
        jButtonLicenciado.setContentAreaFilled(false);
        jButtonLicenciado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLicenciado.setFocusPainted(false);
        jButtonLicenciado.setFocusable(false);
        jButtonLicenciado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonLicenciado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLicenciado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/student.png"))); // NOI18N
        jButtonLicenciado.setMaximumSize(new java.awt.Dimension(110, 80));
        jButtonLicenciado.setMinimumSize(new java.awt.Dimension(110, 80));
        jButtonLicenciado.setPreferredSize(new java.awt.Dimension(110, 80));
        jButtonLicenciado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/student (2).png"))); // NOI18N
        jButtonLicenciado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLicenciado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonLicenciadoMouseMoved(evt);
            }
        });
        jButtonLicenciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLicenciadoMouseExited(evt);
            }
        });
        jButtonLicenciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLicenciadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLicenciadoLayout = new javax.swing.GroupLayout(jPanelLicenciado);
        jPanelLicenciado.setLayout(jPanelLicenciadoLayout);
        jPanelLicenciadoLayout.setHorizontalGroup(
            jPanelLicenciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelLicenciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLicenciadoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonLicenciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelLicenciadoLayout.setVerticalGroup(
            jPanelLicenciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelLicenciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLicenciadoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonLicenciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTitulo.add(jPanelLicenciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jPanelIngeniero.setAlignmentX(0.0F);
        jPanelIngeniero.setAlignmentY(0.0F);
        jPanelIngeniero.setMaximumSize(new java.awt.Dimension(110, 80));
        jPanelIngeniero.setMinimumSize(new java.awt.Dimension(110, 80));
        jPanelIngeniero.setOpaque(false);

        GroupTitulo.add(jButtonIngeniero);
        jButtonIngeniero.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jButtonIngeniero.setForeground(new java.awt.Color(0, 153, 204));
        jButtonIngeniero.setText("Ingeniero");
        jButtonIngeniero.setContentAreaFilled(false);
        jButtonIngeniero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonIngeniero.setFocusPainted(false);
        jButtonIngeniero.setFocusable(false);
        jButtonIngeniero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonIngeniero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonIngeniero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/worker.png"))); // NOI18N
        jButtonIngeniero.setMaximumSize(new java.awt.Dimension(110, 80));
        jButtonIngeniero.setMinimumSize(new java.awt.Dimension(110, 80));
        jButtonIngeniero.setPreferredSize(new java.awt.Dimension(110, 80));
        jButtonIngeniero.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/worker (1).png"))); // NOI18N
        jButtonIngeniero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonIngeniero.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonIngenieroMouseMoved(evt);
            }
        });
        jButtonIngeniero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIngenieroMouseExited(evt);
            }
        });
        jButtonIngeniero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngenieroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIngenieroLayout = new javax.swing.GroupLayout(jPanelIngeniero);
        jPanelIngeniero.setLayout(jPanelIngenieroLayout);
        jPanelIngenieroLayout.setHorizontalGroup(
            jPanelIngenieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelIngenieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelIngenieroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonIngeniero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelIngenieroLayout.setVerticalGroup(
            jPanelIngenieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelIngenieroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelIngenieroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonIngeniero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTitulo.add(jPanelIngeniero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanelTecnico.setAlignmentX(0.0F);
        jPanelTecnico.setAlignmentY(0.0F);
        jPanelTecnico.setMaximumSize(new java.awt.Dimension(110, 80));
        jPanelTecnico.setMinimumSize(new java.awt.Dimension(110, 80));
        jPanelTecnico.setOpaque(false);

        GroupTitulo.add(jButtonTecnico);
        jButtonTecnico.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jButtonTecnico.setForeground(new java.awt.Color(0, 153, 204));
        jButtonTecnico.setText("TSU");
        jButtonTecnico.setContentAreaFilled(false);
        jButtonTecnico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonTecnico.setFocusPainted(false);
        jButtonTecnico.setFocusable(false);
        jButtonTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonTecnico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/professor.png"))); // NOI18N
        jButtonTecnico.setMaximumSize(new java.awt.Dimension(110, 80));
        jButtonTecnico.setMinimumSize(new java.awt.Dimension(110, 80));
        jButtonTecnico.setPreferredSize(new java.awt.Dimension(110, 80));
        jButtonTecnico.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/professor (1).png"))); // NOI18N
        jButtonTecnico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTecnico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonTecnicoMouseMoved(evt);
            }
        });
        jButtonTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTecnicoMouseExited(evt);
            }
        });
        jButtonTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTecnicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTecnicoLayout = new javax.swing.GroupLayout(jPanelTecnico);
        jPanelTecnico.setLayout(jPanelTecnicoLayout);
        jPanelTecnicoLayout.setHorizontalGroup(
            jPanelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTecnicoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelTecnicoLayout.setVerticalGroup(
            jPanelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTecnicoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTitulo.add(jPanelTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jPanelMagister.setAlignmentX(0.0F);
        jPanelMagister.setAlignmentY(0.0F);
        jPanelMagister.setMaximumSize(new java.awt.Dimension(110, 80));
        jPanelMagister.setMinimumSize(new java.awt.Dimension(110, 80));
        jPanelMagister.setOpaque(false);

        GroupTitulo.add(jButtonMagister);
        jButtonMagister.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jButtonMagister.setForeground(new java.awt.Color(0, 153, 204));
        jButtonMagister.setText("Magister");
        jButtonMagister.setContentAreaFilled(false);
        jButtonMagister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonMagister.setFocusPainted(false);
        jButtonMagister.setFocusable(false);
        jButtonMagister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonMagister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMagister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/technician.png"))); // NOI18N
        jButtonMagister.setMaximumSize(new java.awt.Dimension(110, 80));
        jButtonMagister.setMinimumSize(new java.awt.Dimension(110, 80));
        jButtonMagister.setPreferredSize(new java.awt.Dimension(110, 80));
        jButtonMagister.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/professional.png"))); // NOI18N
        jButtonMagister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMagister.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonMagisterMouseMoved(evt);
            }
        });
        jButtonMagister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMagisterMouseExited(evt);
            }
        });
        jButtonMagister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMagisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMagisterLayout = new javax.swing.GroupLayout(jPanelMagister);
        jPanelMagister.setLayout(jPanelMagisterLayout);
        jPanelMagisterLayout.setHorizontalGroup(
            jPanelMagisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelMagisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMagisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonMagister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelMagisterLayout.setVerticalGroup(
            jPanelMagisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelMagisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMagisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonMagister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTitulo.add(jPanelMagister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanelDoctor.setAlignmentX(0.0F);
        jPanelDoctor.setAlignmentY(0.0F);
        jPanelDoctor.setMaximumSize(new java.awt.Dimension(110, 80));
        jPanelDoctor.setMinimumSize(new java.awt.Dimension(110, 80));
        jPanelDoctor.setOpaque(false);

        GroupTitulo.add(jButtonDoctor);
        jButtonDoctor.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16)); // NOI18N
        jButtonDoctor.setForeground(new java.awt.Color(0, 153, 204));
        jButtonDoctor.setText("Doctor");
        jButtonDoctor.setContentAreaFilled(false);
        jButtonDoctor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonDoctor.setFocusPainted(false);
        jButtonDoctor.setFocusable(false);
        jButtonDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonDoctor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/professor (2).png"))); // NOI18N
        jButtonDoctor.setMaximumSize(new java.awt.Dimension(110, 80));
        jButtonDoctor.setMinimumSize(new java.awt.Dimension(110, 80));
        jButtonDoctor.setPreferredSize(new java.awt.Dimension(110, 80));
        jButtonDoctor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/professor (3).png"))); // NOI18N
        jButtonDoctor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDoctor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonDoctorMouseMoved(evt);
            }
        });
        jButtonDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDoctorMouseExited(evt);
            }
        });
        jButtonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDoctorLayout = new javax.swing.GroupLayout(jPanelDoctor);
        jPanelDoctor.setLayout(jPanelDoctorLayout);
        jPanelDoctorLayout.setHorizontalGroup(
            jPanelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDoctorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelDoctorLayout.setVerticalGroup(
            jPanelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDoctorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButtonDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTitulo.add(jPanelDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jPPage1.add(jPanelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 260, 290));

        jPanelEspecilidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESPECIALIDAD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelEspecilidades.setOpaque(false);
        jPanelEspecilidades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelComp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelComp.setOpaque(false);
        jPanelComp.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelComp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelCompMouseMoved(evt);
            }
        });
        jPanelComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCompMouseExited(evt);
            }
        });
        jPanelComp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GroupEspecialidades.add(jButtonComputacion);
        jButtonComputacion.setContentAreaFilled(false);
        jButtonComputacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonComputacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonComputacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonComputacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_workstation_50px_1.png"))); // NOI18N
        jButtonComputacion.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonComputacion.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonComputacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_workstation_50px.png"))); // NOI18N
        jButtonComputacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonComputacionMouseMoved(evt);
            }
        });
        jButtonComputacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonComputacionMouseExited(evt);
            }
        });
        jButtonComputacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComputacionActionPerformed(evt);
            }
        });
        jPanelComp.add(jButtonComputacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        jPanelEspecilidades.add(jPanelComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, 60));

        jPanelInformatica.setOpaque(false);
        jPanelInformatica.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelInformaticaMouseMoved(evt);
            }
        });
        jPanelInformatica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelInformaticaMouseExited(evt);
            }
        });
        jPanelInformatica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GroupEspecialidades.add(jButtonInformatica);
        jButtonInformatica.setAlignmentX(0.5F);
        jButtonInformatica.setContentAreaFilled(false);
        jButtonInformatica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonInformatica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonInformatica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInformatica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_informatics_50px_1.png"))); // NOI18N
        jButtonInformatica.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonInformatica.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_informatics_50px_2.png"))); // NOI18N
        jButtonInformatica.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonInformaticaMouseMoved(evt);
            }
        });
        jButtonInformatica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonInformaticaMouseExited(evt);
            }
        });
        jButtonInformatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformaticaActionPerformed(evt);
            }
        });
        jPanelInformatica.add(jButtonInformatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanelEspecilidades.add(jPanelInformatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 60, 60));

        jPanelSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelSistema.setOpaque(false);
        jPanelSistema.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelSistema.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelSistemaMouseMoved(evt);
            }
        });
        jPanelSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSistemaMouseExited(evt);
            }
        });
        jPanelSistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GroupEspecialidades.add(jButtonSistema);
        jButtonSistema.setContentAreaFilled(false);
        jButtonSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButtonSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_working_with_a_laptop_50px_1.png"))); // NOI18N
        jButtonSistema.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_working_with_a_laptop_50px.png"))); // NOI18N
        jButtonSistema.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonSistemaMouseMoved(evt);
            }
        });
        jButtonSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSistemaMouseExited(evt);
            }
        });
        jButtonSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSistemaActionPerformed(evt);
            }
        });
        jPanelSistema.add(jButtonSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanelEspecilidades.add(jPanelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 60, 60));

        jTexComputacion.setEditable(false);
        jTexComputacion.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jTexComputacion.setForeground(new java.awt.Color(0, 153, 204));
        jTexComputacion.setText("Comp.");
        jTexComputacion.setBorder(null);
        jTexComputacion.setFocusable(false);
        jTexComputacion.setOpaque(false);
        jTexComputacion.setRequestFocusEnabled(false);
        jPanelEspecilidades.add(jTexComputacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 30));

        jTextInformatica.setEditable(false);
        jTextInformatica.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jTextInformatica.setForeground(new java.awt.Color(0, 153, 204));
        jTextInformatica.setText("Informática");
        jTextInformatica.setBorder(null);
        jTextInformatica.setFocusable(false);
        jTextInformatica.setOpaque(false);
        jTextInformatica.setRequestFocusEnabled(false);
        jPanelEspecilidades.add(jTextInformatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, 30));

        jTextSistema.setEditable(false);
        jTextSistema.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jTextSistema.setForeground(new java.awt.Color(0, 153, 204));
        jTextSistema.setText("Sistema");
        jTextSistema.setBorder(null);
        jTextSistema.setOpaque(false);
        jPanelEspecilidades.add(jTextSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 60, 30));

        jPPage1.add(jPanelEspecilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 260, 130));

        jPanelHerramientas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelHerramientas.setOpaque(false);
        jPanelHerramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("HERRAMIENTAS");
        jPanelHerramientas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelHerramientas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 400, -1));

        jPanelCuadroHerramientas.setMaximumSize(new java.awt.Dimension(380, 370));
        jPanelCuadroHerramientas.setMinimumSize(new java.awt.Dimension(380, 370));
        jPanelCuadroHerramientas.setOpaque(false);
        jPanelCuadroHerramientas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCertificaciones.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCertificaciones.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButtonCertificaciones.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCertificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaAzul - copia.png"))); // NOI18N
        jButtonCertificaciones.setText("+ Certificaciones");
        jButtonCertificaciones.setBorderPainted(false);
        jButtonCertificaciones.setContentAreaFilled(false);
        jButtonCertificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCertificaciones.setFocusPainted(false);
        jButtonCertificaciones.setIconTextGap(-155);
        jButtonCertificaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonCertificaciones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonCertificaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonCertificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCertificacionesActionPerformed(evt);
            }
        });
        jPanelCuadroHerramientas.add(jButtonCertificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jComboBoxCertificaciones.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBoxCertificaciones.setForeground(new java.awt.Color(0, 153, 204));
        jComboBoxCertificaciones.setAlignmentX(0.0F);
        jComboBoxCertificaciones.setBorder(null);
        jComboBoxCertificaciones.setFocusable(false);
        jComboBoxCertificaciones.setMaximumSize(new java.awt.Dimension(195, 48));
        jComboBoxCertificaciones.setMinimumSize(new java.awt.Dimension(195, 48));
        jComboBoxCertificaciones.setOpaque(false);
        jComboBoxCertificaciones.setPreferredSize(new java.awt.Dimension(195, 48));
        jPanelCuadroHerramientas.add(jComboBoxCertificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 180, 30));

        jButtonHerramientas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonHerramientas.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButtonHerramientas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaAzul - copia.png"))); // NOI18N
        jButtonHerramientas.setText("+ Herramientas");
        jButtonHerramientas.setBorderPainted(false);
        jButtonHerramientas.setContentAreaFilled(false);
        jButtonHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonHerramientas.setFocusPainted(false);
        jButtonHerramientas.setIconTextGap(-155);
        jButtonHerramientas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonHerramientas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonHerramientas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHerramientasActionPerformed(evt);
            }
        });
        jPanelCuadroHerramientas.add(jButtonHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 50));

        jComboBoxHerramientas.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBoxHerramientas.setForeground(new java.awt.Color(0, 153, 204));
        jComboBoxHerramientas.setAlignmentX(0.0F);
        jComboBoxHerramientas.setBorder(null);
        jComboBoxHerramientas.setFocusable(false);
        jComboBoxHerramientas.setMaximumSize(new java.awt.Dimension(195, 48));
        jComboBoxHerramientas.setMinimumSize(new java.awt.Dimension(195, 48));
        jComboBoxHerramientas.setOpaque(false);
        jComboBoxHerramientas.setPreferredSize(new java.awt.Dimension(195, 48));
        jPanelCuadroHerramientas.add(jComboBoxHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, 30));

        jButtonConocGenerales.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConocGenerales.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButtonConocGenerales.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConocGenerales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaAzul - copia.png"))); // NOI18N
        jButtonConocGenerales.setText("+ C. generales");
        jButtonConocGenerales.setBorderPainted(false);
        jButtonConocGenerales.setContentAreaFilled(false);
        jButtonConocGenerales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConocGenerales.setIconTextGap(-155);
        jButtonConocGenerales.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonConocGenerales.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonConocGenerales.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonConocGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConocGeneralesActionPerformed(evt);
            }
        });
        jPanelCuadroHerramientas.add(jButtonConocGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 50));

        jComboBoxCGenerales.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBoxCGenerales.setForeground(new java.awt.Color(0, 153, 204));
        jComboBoxCGenerales.setAlignmentX(0.0F);
        jComboBoxCGenerales.setBorder(null);
        jComboBoxCGenerales.setFocusable(false);
        jComboBoxCGenerales.setMaximumSize(new java.awt.Dimension(195, 48));
        jComboBoxCGenerales.setMinimumSize(new java.awt.Dimension(195, 48));
        jComboBoxCGenerales.setOpaque(false);
        jComboBoxCGenerales.setPreferredSize(new java.awt.Dimension(195, 48));
        jPanelCuadroHerramientas.add(jComboBoxCGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 30));

        jButtonExpLaborales.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExpLaborales.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButtonExpLaborales.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExpLaborales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaAzul - copia.png"))); // NOI18N
        jButtonExpLaborales.setText("+ Exps. laborales");
        jButtonExpLaborales.setBorderPainted(false);
        jButtonExpLaborales.setContentAreaFilled(false);
        jButtonExpLaborales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonExpLaborales.setIconTextGap(-155);
        jButtonExpLaborales.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonExpLaborales.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonExpLaborales.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonExpLaborales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpLaboralesActionPerformed(evt);
            }
        });
        jPanelCuadroHerramientas.add(jButtonExpLaborales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 50));

        jComboBoxExpsLaborales.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBoxExpsLaborales.setForeground(new java.awt.Color(0, 153, 204));
        jComboBoxExpsLaborales.setAlignmentX(0.0F);
        jComboBoxExpsLaborales.setBorder(null);
        jComboBoxExpsLaborales.setFocusable(false);
        jComboBoxExpsLaborales.setMaximumSize(new java.awt.Dimension(195, 48));
        jComboBoxExpsLaborales.setMinimumSize(new java.awt.Dimension(195, 48));
        jComboBoxExpsLaborales.setOpaque(false);
        jComboBoxExpsLaborales.setPreferredSize(new java.awt.Dimension(195, 48));
        jPanelCuadroHerramientas.add(jComboBoxExpsLaborales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 180, 30));

        jButtonLenguajes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLenguajes.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButtonLenguajes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLenguajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaAzul - copia.png"))); // NOI18N
        jButtonLenguajes.setText("+ Lenguajes");
        jButtonLenguajes.setBorderPainted(false);
        jButtonLenguajes.setContentAreaFilled(false);
        jButtonLenguajes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLenguajes.setIconTextGap(-155);
        jButtonLenguajes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonLenguajes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonLenguajes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EtiquetaNaranja - copia.png"))); // NOI18N
        jButtonLenguajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLenguajesActionPerformed(evt);
            }
        });
        jPanelCuadroHerramientas.add(jButtonLenguajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 50));

        jComboBoxLenguajes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBoxLenguajes.setForeground(new java.awt.Color(0, 153, 204));
        jComboBoxLenguajes.setAlignmentX(0.0F);
        jComboBoxLenguajes.setBorder(null);
        jComboBoxLenguajes.setFocusable(false);
        jComboBoxLenguajes.setMaximumSize(new java.awt.Dimension(195, 48));
        jComboBoxLenguajes.setMinimumSize(new java.awt.Dimension(195, 48));
        jComboBoxLenguajes.setOpaque(false);
        jComboBoxLenguajes.setPreferredSize(new java.awt.Dimension(195, 48));
        jPanelCuadroHerramientas.add(jComboBoxLenguajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 180, 30));

        jPanelHerramientas.add(jPanelCuadroHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 370));

        jPPage1.add(jPanelHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 400, 420));

        jCancel.setBackground(new java.awt.Color(0, 51, 51));
        jCancel.setForeground(new java.awt.Color(0, 51, 51));
        jCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px.png"))); // NOI18N
        jCancel.setBorderPainted(false);
        jCancel.setContentAreaFilled(false);
        jCancel.setPreferredSize(new java.awt.Dimension(40, 40));
        jCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCancelMouseClicked(evt);
            }
        });
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jPPage1.add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 60, 60));

        jNext.setBackground(new java.awt.Color(0, 51, 51));
        jNext.setForeground(new java.awt.Color(0, 51, 51));
        jNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_approval_80px.png"))); // NOI18N
        jNext.setBorderPainted(false);
        jNext.setContentAreaFilled(false);
        jNext.setPreferredSize(new java.awt.Dimension(40, 40));
        jNext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_approval_80px_1.png"))); // NOI18N
        jNext.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_approval_80px_1.png"))); // NOI18N
        jNext.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_approval_80px_1.png"))); // NOI18N
        jNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNextMouseClicked(evt);
            }
        });
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        jPPage1.add(jNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 60, 60));

        jPConcTec.add(jPPage1);
        jPPage1.setBounds(0, 0, 950, 670);

        jBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg1.gif"))); // NOI18N
        jBackGround.setMaximumSize(new java.awt.Dimension(950, 650));
        jBackGround.setMinimumSize(new java.awt.Dimension(950, 650));
        jBackGround.setPreferredSize(new java.awt.Dimension(950, 700));
        jPConcTec.add(jBackGround);
        jBackGround.setBounds(0, 0, 950, 670);

        getContentPane().add(jPConcTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 950, 670));

        jPanelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(950, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(894, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 30));

        jPanelLateral.setBackground(new java.awt.Color(0, 51, 51));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(50, 700));

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCancelMouseClicked
 
    }//GEN-LAST:event_jCancelMouseClicked

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
      Dialogs d = new Dialogs(2);
        d.setVisible(true);
    
        if(d.getState() == true){   
            eliminarPostulanteDatabase();
            mp = new Menu_Principal(connection);
            mp.setVisible(true);
	    dispose();
        }
    }//GEN-LAST:event_jCancelActionPerformed

    private void jNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextMouseClicked

    }//GEN-LAST:event_jNextMouseClicked

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
                   if(opc_titulo == 1) nuevo_postulante.setTitulo("Bachiller");
                   if(opc_titulo == 2) nuevo_postulante.setTitulo("Licenciado");
                   if(opc_titulo == 3) nuevo_postulante.setTitulo("Ingeniero");
                   if(opc_titulo == 4) nuevo_postulante.setTitulo("Tecnico Superior");
                   if(opc_titulo == 5) nuevo_postulante.setTitulo("Magister");
                   if(opc_titulo == 6) nuevo_postulante.setTitulo("Doctor");

                    if(opc_especialidad == 1) nuevo_postulante.setEspecialidad("Computación");
                    if(opc_especialidad == 2) nuevo_postulante.setEspecialidad("Informatica");
                    if(opc_especialidad == 3) nuevo_postulante.setEspecialidad("Sistemas");
                    
                    if( (!jButtonBachiller.isSelected() && !jButtonDoctor.isSelected() && !jButtonMagister.isSelected() && !jButtonIngeniero.isSelected() && !jButtonLicenciado.isSelected() && !jButtonTecnico.isSelected()) || (!jButtonComputacion.isSelected() && !jButtonInformatica.isSelected() && !jButtonSistema.isSelected())){
                         Dialogs d = new Dialogs(6); //FORMULARIO INCOMPLETO
                         d.setVisible(true);
                         return;
                    }

                    agregarPostulanteNivelAcademicoDatabase();
                                
                    Menu_Principal mp = new Menu_Principal(connection);
                    mp.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jNextActionPerformed

    
    private void jButtonBachillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBachillerActionPerformed
        opc_titulo = 1;
    }//GEN-LAST:event_jButtonBachillerActionPerformed

    private void jButtonLicenciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLicenciadoActionPerformed
        opc_titulo = 2;
    }//GEN-LAST:event_jButtonLicenciadoActionPerformed

    private void jButtonIngenieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngenieroActionPerformed
        opc_titulo = 3;
    }//GEN-LAST:event_jButtonIngenieroActionPerformed

    private void jButtonTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTecnicoActionPerformed
        opc_titulo = 4;
    }//GEN-LAST:event_jButtonTecnicoActionPerformed

    private void jButtonMagisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMagisterActionPerformed
        opc_titulo = 5;
    }//GEN-LAST:event_jButtonMagisterActionPerformed

    private void jButtonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorActionPerformed
        opc_titulo = 6;
    }//GEN-LAST:event_jButtonDoctorActionPerformed

    private void jButtonComputacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComputacionActionPerformed
        opc_especialidad = 1;
    }//GEN-LAST:event_jButtonComputacionActionPerformed

    private void jButtonInformaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformaticaActionPerformed
        opc_especialidad = 2;
    }//GEN-LAST:event_jButtonInformaticaActionPerformed

    private void jButtonConocGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConocGeneralesActionPerformed
        ToSendDatabaseFrame tsdf = new ToSendDatabaseFrame(this, id_postulante, 2, connection);
        tsdf.setVisible(true);
    }//GEN-LAST:event_jButtonConocGeneralesActionPerformed

    private void jButtonSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSistemaActionPerformed
        opc_especialidad = 3;
    }//GEN-LAST:event_jButtonSistemaActionPerformed

    private void jPanelCompMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCompMouseMoved
       jPanelComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jPanelCompMouseMoved

    private void jPanelInformaticaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInformaticaMouseMoved
       jPanelInformatica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jPanelInformaticaMouseMoved

    private void jPanelSistemaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSistemaMouseMoved
       jPanelSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jPanelSistemaMouseMoved

    private void jPanelCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCompMouseExited
        jPanelComp.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jPanelCompMouseExited

    private void jPanelInformaticaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInformaticaMouseExited
        jPanelInformatica.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jPanelInformaticaMouseExited

    private void jPanelSistemaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSistemaMouseExited
        jPanelSistema.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jPanelSistemaMouseExited

    private void jButtonComputacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonComputacionMouseMoved
        jPanelComp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonComputacionMouseMoved

    private void jButtonComputacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonComputacionMouseExited
        jPanelComp.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonComputacionMouseExited

    private void jButtonInformaticaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInformaticaMouseMoved
        jPanelInformatica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonInformaticaMouseMoved

    private void jButtonInformaticaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInformaticaMouseExited
        jPanelInformatica.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonInformaticaMouseExited

    private void jButtonSistemaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSistemaMouseMoved
        jPanelSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonSistemaMouseMoved

    private void jButtonSistemaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSistemaMouseExited
        jPanelSistema.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonSistemaMouseExited

    private void jButtonHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHerramientasActionPerformed
        ToSendDatabaseFrame tsdf = new ToSendDatabaseFrame(this, id_postulante, 1, connection);
        tsdf.setVisible(true);
    }//GEN-LAST:event_jButtonHerramientasActionPerformed

    private void jButtonExpLaboralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpLaboralesActionPerformed
        ToSendDatabaseFrame tsdf = new ToSendDatabaseFrame(this, id_postulante, 3, connection);
        tsdf.setVisible(true);
    }//GEN-LAST:event_jButtonExpLaboralesActionPerformed

    private void jButtonLenguajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLenguajesActionPerformed
        ToSendDatabaseFrame tsdf = new ToSendDatabaseFrame(this, id_postulante, 4, connection);
        tsdf.setVisible(true);
    }//GEN-LAST:event_jButtonLenguajesActionPerformed

    private void jButtonCertificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCertificacionesActionPerformed
        ToSendDatabaseFrame tsdf = new ToSendDatabaseFrame(this ,id_postulante, 0, connection);
        tsdf.setVisible(true);       
        
    }//GEN-LAST:event_jButtonCertificacionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setState(Formulario_Postulante_Info_Personal.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBachillerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBachillerMouseExited
       jPanelBachiller.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonBachillerMouseExited

    private void jButtonLicenciadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLicenciadoMouseExited
        jPanelLicenciado.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonLicenciadoMouseExited

    private void jButtonIngenieroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngenieroMouseExited
        jPanelIngeniero.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonIngenieroMouseExited

    private void jButtonTecnicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTecnicoMouseExited
        jPanelTecnico.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonTecnicoMouseExited

    private void jButtonMagisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMagisterMouseExited
        jPanelMagister.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonMagisterMouseExited

    private void jButtonDoctorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDoctorMouseExited
        jPanelDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jButtonDoctorMouseExited

    private void jButtonBachillerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBachillerMouseMoved
        jPanelBachiller.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonBachillerMouseMoved

    private void jButtonLicenciadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLicenciadoMouseMoved
        jPanelLicenciado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonLicenciadoMouseMoved

    private void jButtonIngenieroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngenieroMouseMoved
        jPanelIngeniero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonIngenieroMouseMoved

    private void jButtonTecnicoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTecnicoMouseMoved
        jPanelTecnico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonTecnicoMouseMoved

    private void jButtonMagisterMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMagisterMouseMoved
        jPanelMagister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonMagisterMouseMoved

    private void jButtonDoctorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDoctorMouseMoved
        jPanelDoctor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jButtonDoctorMouseMoved

       
    public void addCertificacion(String certificacion){
        jComboBoxCertificaciones.addItem(certificacion);
    }
    
    public void addHerramienta(String herramienta){
        jComboBoxHerramientas.addItem(herramienta);
    }
    public void addCGeneral(String cgeneral){
        jComboBoxCGenerales.addItem(cgeneral);
    }
    public void addExpLaboral(String explabo){
        jComboBoxExpsLaborales.addItem(explabo);
    }
    public void addLenguaje(String lenguaje){
        jComboBoxLenguajes.addItem(lenguaje);
    }
    
    private int getIdPostulanteDatabase(String postulante_correo){
        
            int id_postulante = 0;
              
             try {
                PreparedStatement ps = connection.prepareStatement("SELECT * FROM postulantes WHERE correo = ?");
                
                ps.setString(1, postulante_correo);
                
                ResultSet rs = ps.executeQuery();
                
                while(rs.next()){
                    id_postulante = Integer.parseInt(rs.getString(1));
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Formulario_Postulante_Conocimientos.class.getName()).log(Level.SEVERE, null, ex);
            }
             
          return id_postulante;
            
        }
       
    public void eliminarPostulanteDatabase(){
        
            // Vamos a eliminar toda la informacion referente al postulante que cancelo su registro.
            try {
                connection.prepareStatement("DELETE FROM `herramientas_manejadas` WHERE `idpostulante` = " + String.valueOf(id_postulante)).executeUpdate();
                
                connection.prepareStatement("DELETE FROM `experiencia_laboral` WHERE `idpostulante` = " + String.valueOf(id_postulante)).executeUpdate();
                
                connection.prepareStatement("DELETE FROM `conocimientos_generales` WHERE `idpostulante` = " + String.valueOf(id_postulante)).executeUpdate();
                
                connection.prepareStatement("DELETE FROM `certificaciones` WHERE `idpostulante` = " + String.valueOf(id_postulante)).executeUpdate();
                
                connection.prepareStatement("DELETE FROM `lenguajes` WHERE `idpostulante` = " + String.valueOf(id_postulante)).executeUpdate();
                
                connection.prepareStatement("DELETE FROM `postulantes` WHERE `idpostulante` = " + String.valueOf(id_postulante)).executeUpdate();
                
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
	
    // Agregamos en la base de datos los conocimientos del postulante.
    public void agregarPostulanteNivelAcademicoDatabase(){
        Dialogs d;
        try {
                PreparedStatement ps = connection.prepareStatement("INSERT INTO `nivelacademico` (`idnivelacademico`, `titulo`, `especialidad`, `idpostulante`) VALUES (NULL, ?, ?, ?)");
                
                ps.setString(1, nuevo_postulante.getTitulo());
                ps.setString(2, nuevo_postulante.getEspecialidad());
                ps.setInt(3, this.id_postulante);
                
                ps.executeUpdate();
                d = new Dialogs(7);
                d.setVisible(true);//CONOCIMIENTOS AGREGADOS CORRECTAMENTE
                
            } catch (SQLException ex) {
                
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
                d = new Dialogs(5);
                d.setVisible(true);//ERROR GENERAL
            }
        }
        
    public void prueba_postulante() {
		System.out.println("Nombres: "+nuevo_postulante.getPrimerNombre() + " " + nuevo_postulante.getSegundoNombre() + "\nApellidos: "+nuevo_postulante.getPrimerApellido() + " " + nuevo_postulante.getSegundoApellido() +"\nEdad: "+nuevo_postulante.getEdad()+"\nSexo: "+nuevo_postulante.getSexo()+"\nPais Origen: "+nuevo_postulante.getPais_origen()+"\nResidencia: "+nuevo_postulante.getResidencia()+"\nTelefono: "+nuevo_postulante.getTelefono()+"\nCorreo: "+nuevo_postulante.getCorreo());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupEspecialidades;
    private javax.swing.ButtonGroup GroupTitulo;
    private javax.swing.JLabel jBackGround;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jButtonBachiller;
    private javax.swing.JButton jButtonCertificaciones;
    private javax.swing.JRadioButton jButtonComputacion;
    private javax.swing.JButton jButtonConocGenerales;
    private javax.swing.JRadioButton jButtonDoctor;
    private javax.swing.JButton jButtonExpLaborales;
    private javax.swing.JButton jButtonHerramientas;
    private javax.swing.JRadioButton jButtonInformatica;
    private javax.swing.JRadioButton jButtonIngeniero;
    private javax.swing.JButton jButtonLenguajes;
    private javax.swing.JRadioButton jButtonLicenciado;
    private javax.swing.JRadioButton jButtonMagister;
    private javax.swing.JRadioButton jButtonSistema;
    private javax.swing.JRadioButton jButtonTecnico;
    private javax.swing.JButton jCancel;
    private javax.swing.JComboBox<String> jComboBoxCGenerales;
    private javax.swing.JComboBox<String> jComboBoxCertificaciones;
    private javax.swing.JComboBox<String> jComboBoxExpsLaborales;
    private javax.swing.JComboBox<String> jComboBoxHerramientas;
    private javax.swing.JComboBox<String> jComboBoxLenguajes;
    private javax.swing.JLabel jConocTecn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jNext;
    private javax.swing.JPanel jPConcTec;
    private javax.swing.JPanel jPPage1;
    private javax.swing.JPanel jPanelBachiller;
    private javax.swing.JPanel jPanelComp;
    private javax.swing.JPanel jPanelCuadroHerramientas;
    private javax.swing.JPanel jPanelDoctor;
    private javax.swing.JPanel jPanelEspecilidades;
    private javax.swing.JPanel jPanelHerramientas;
    private javax.swing.JPanel jPanelInformatica;
    private javax.swing.JPanel jPanelIngeniero;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelLicenciado;
    private javax.swing.JPanel jPanelMagister;
    private javax.swing.JPanel jPanelSistema;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPanel jPanelTecnico;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTexComputacion;
    private javax.swing.JTextField jTextInformatica;
    private javax.swing.JTextField jTextSistema;
    // End of variables declaration//GEN-END:variables
}
