/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.*;
import java.sql.*;
import java.util.logging.*;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import Controllers.Administracion_json;
/**
 *
 * @author Jesus Gonzalez
 */
public class ToSendDatabaseEmpleoFrame extends javax.swing.JDialog {
      private int id_ofertaempleo, option;
      Connection connection;
      Formulario_Empleo_Conocimientos fep;
    /**
     * Creates new form NEWToSendDatabaseEmpleoFrame
     */
    public ToSendDatabaseEmpleoFrame(Formulario_Empleo_Conocimientos fep, int id_ofertaempleo, int option, Connection connection) {
        initComponents();
        setModal(true);
        setBackground(new Color(1.0f,1.0f,1.0f,0.5f)); 
        setLocationRelativeTo(null);
        
        generarLabelFuncion(option);       
        
        this.fep= fep;
        this.id_ofertaempleo = id_ofertaempleo;   
        this.option = option;
        this.connection = connection; 
        
    }

        //Metodo para indicar la operacion a realizar dependiendo de las opciones.
    public void generarLabelFuncion(int option){
        Font font = new Font("Tahoma", Font.BOLD, 16);
        switch(option){
            case 1: jTextField1.setBorder(new TitledBorder(new LineBorder(new Color(0, 153, 240)), "Ingrese una herramienta:", TitledBorder.LEADING,
            TitledBorder.TOP, font , new Color(0, 102, 102 )));    
                    break;
            case 2: jTextField1.setBorder(new TitledBorder(new LineBorder(new Color(0, 153, 240)), "Ingrese una certificación:", TitledBorder.LEADING,
            TitledBorder.TOP, font , new Color(0, 102, 102 )));
                    break;
            case 3: jTextField1.setBorder(new TitledBorder(new LineBorder(new Color(0, 153, 240)), "Ingrese un lenguaje:", TitledBorder.LEADING,
            TitledBorder.TOP, font , new Color(0, 102, 102 )));
                    break;
        }
    }
    
        // Seleccionando la opcion dependiendo del conocimiento que el postulante desea ingresar.
    public void selectOptionDatabase(int option){
    
        switch(option){
            case 1: agregarHerramientasOfertaEmpleoDatabase();
                    break;
            case 2: agregarCertificacionesOfertaEmpleoDatabase();
                    break;
            case 3: agregarLenguajesOfertaEmpleoDatabase();
                    break;
        }
    }
    
    // Almacenar en la base de datos las herramientas oferta empleo del postulante.
    public void agregarHerramientasOfertaEmpleoDatabase(){
        
            try {
                PreparedStatement ps = connection.prepareStatement("INSERT INTO `herramientas_ofertaempleo` (`idherramienta_oferta`, `herramienta`, `idoferta_empleo`) VALUES (NULL, ?, ?)");
                
                ps.setString(1, jTextField1.getText());
                ps.setInt(2, id_ofertaempleo);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    // Almacenar en la base de datos las certificaciones de oferta empleo del postulante.
    public void agregarCertificacionesOfertaEmpleoDatabase(){
        
            try {
                PreparedStatement ps = connection.prepareStatement("INSERT INTO `certificaciones_ofertaempleo` (`idcertificacion_ofertaempleo`, `certificacion`, `idoferta_empleo`) VALUES (NULL, ?, ?)");
                
                ps.setString(1, jTextField1.getText());
                ps.setInt(2, id_ofertaempleo);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    // Almacenar en la base de datos las certificaciones de oferta empleo del postulante.
    public void agregarLenguajesOfertaEmpleoDatabase(){
        
            try {
                PreparedStatement ps = connection.prepareStatement("INSERT INTO `lenguajes_ofertaempleo` (`idlenguaje_oferta`, `nombrelenguaje`, `idoferta_empleo`) VALUES (NULL, ?, ?)");
                
                ps.setString(1, jTextField1.getText());
                ps.setInt(2, id_ofertaempleo);
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonAccept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 250));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 240));
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 153, 240))); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 270, 50));

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_2_60px_1.png"))); // NOI18N
        jButtonCancel.setBorder(null);
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.setContentAreaFilled(false);
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.setFocusable(false);
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancel.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_2_60px.png"))); // NOI18N
        jButtonCancel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_2_60px.png"))); // NOI18N
        jButtonCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_2_60px.png"))); // NOI18N
        jButtonCancel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jButtonCancelComponentHidden(evt);
            }
        });
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jButtonAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_checkmark_60px.png"))); // NOI18N
        jButtonAccept.setBorderPainted(false);
        jButtonAccept.setContentAreaFilled(false);
        jButtonAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAccept.setFocusPainted(false);
        jButtonAccept.setFocusable(false);
        jButtonAccept.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonAccept.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonAccept.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonAccept.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_checkmark_60px_1.png"))); // NOI18N
        jButtonAccept.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_checkmark_60px_1.png"))); // NOI18N
        jButtonAccept.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_checkmark_60px_1.png"))); // NOI18N
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/little background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButtonCancelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelComponentHidden

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
         dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        if(!jTextField1.getText().equals("")){
            selectOptionDatabase(option);
            switch(option)
                    {
                        case 1:
                            fep.addHerramienta(jTextField1.getText());
                            break;
                        case 2:
                            fep.addCertificacion(jTextField1.getText());
                            break;
                        case 3:
                            fep.addCGeneral(jTextField1.getText());
                            break;

                        default: break;
                    }        
            dispose();
        }
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jPanel1formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formAncestorAdded

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
