package Views;

import Models.Postulante;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import Controllers.Administracion_json;

public class Formulario_Postulante_Info_Personal extends javax.swing.JFrame {

    private Menu_Principal mp;
    Formulario_Postulante_Conocimientos fpc;
    private Postulante nuevo_postulante;
    Connection connection;
        
    public Formulario_Postulante_Info_Personal(Connection connection) {
        
        initComponents();  
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        
        // Conectando a la base de datos.
        this.connection = connection;
        //Cargar paises de BDD
        cargarPaises();
        carga_edades();        
        nuevo_postulante = new Postulante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPIngreso = new javax.swing.JPanel();
        jPPage1 = new javax.swing.JPanel();
        jInfPersonal = new javax.swing.JLabel();
        jAvatar = new javax.swing.JLabel();
        jPDATOS = new javax.swing.JPanel();
        jTextNOMBRE = new javax.swing.JTextField();
        jSepNOMBRE = new javax.swing.JSeparator();
        jTextNOMBRE1 = new javax.swing.JTextField();
        jSepNOMBRE1 = new javax.swing.JSeparator();
        jTextAPELLIDO = new javax.swing.JTextField();
        jSepAPELLIDO = new javax.swing.JSeparator();
        jTextAPELLIDO2 = new javax.swing.JTextField();
        jSepAPELLIDO2 = new javax.swing.JSeparator();
        jTextDNI = new javax.swing.JTextField();
        jSepDNI = new javax.swing.JSeparator();
        jSexo = new javax.swing.JPanel();
        jPanelFenm = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanelMan = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanelLocal = new javax.swing.JPanel();
        jPaisDeOrigen = new javax.swing.JPanel();
        jComboPais = new javax.swing.JComboBox<>();
        jResidencia = new javax.swing.JPanel();
        jComboResidencia = new javax.swing.JComboBox<>();
        jPanelContacto = new javax.swing.JPanel();
        jTextTelefono = new javax.swing.JTextField();
        jSepTelefono = new javax.swing.JSeparator();
        jTextCorreo = new javax.swing.JTextField();
        jSepCorreo = new javax.swing.JSeparator();
        jComboBoxCorreo = new javax.swing.JComboBox<>();
        jCancel = new javax.swing.JButton();
        jNext = new javax.swing.JButton();
        jPanelEdad = new javax.swing.JPanel();
        jComboEdad = new javax.swing.JComboBox<>();
        jBackGround = new javax.swing.JLabel();
        jPanelSuperior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelLateral = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPIngreso.setBackground(new java.awt.Color(3, 153, 129));
        jPIngreso.setPreferredSize(new java.awt.Dimension(950, 670));
        jPIngreso.setLayout(null);

        jPPage1.setBackground(new java.awt.Color(255, 255, 255));
        jPPage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPPage1.setOpaque(false);
        jPPage1.setPreferredSize(new java.awt.Dimension(950, 670));
        jPPage1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPPage1MouseMoved(evt);
            }
        });
        jPPage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInfPersonal.setFont(new java.awt.Font("Dosis", 1, 36)); // NOI18N
        jInfPersonal.setText("INFORMACIÓN PERSONAL");
        jPPage1.add(jInfPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 60));

        jAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_name_120px_1.png"))); // NOI18N
        jPPage1.add(jAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 120));

        jPDATOS.setOpaque(false);

        jTextNOMBRE.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jTextNOMBRE.setForeground(new java.awt.Color(0, 153, 204));
        jTextNOMBRE.setText("NOMBRE");
        jTextNOMBRE.setBorder(null);
        jTextNOMBRE.setOpaque(false);
        jTextNOMBRE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNOMBREFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNOMBREFocusLost(evt);
            }
        });
        jTextNOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNOMBREKeyTyped(evt);
            }
        });

        jTextNOMBRE1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jTextNOMBRE1.setForeground(new java.awt.Color(0, 153, 204));
        jTextNOMBRE1.setText("NOMBRE (SEGUNDO)");
        jTextNOMBRE1.setBorder(null);
        jTextNOMBRE1.setOpaque(false);
        jTextNOMBRE1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNOMBRE1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNOMBRE1FocusLost(evt);
            }
        });
        jTextNOMBRE1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNOMBRE1KeyTyped(evt);
            }
        });

        jTextAPELLIDO.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jTextAPELLIDO.setForeground(new java.awt.Color(0, 153, 204));
        jTextAPELLIDO.setText("APELLIDO");
        jTextAPELLIDO.setBorder(null);
        jTextAPELLIDO.setOpaque(false);
        jTextAPELLIDO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAPELLIDOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAPELLIDOFocusLost(evt);
            }
        });
        jTextAPELLIDO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAPELLIDOKeyTyped(evt);
            }
        });

        jTextAPELLIDO2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jTextAPELLIDO2.setForeground(new java.awt.Color(0, 153, 204));
        jTextAPELLIDO2.setText("APELLIDO (SEGUNDO)");
        jTextAPELLIDO2.setBorder(null);
        jTextAPELLIDO2.setOpaque(false);
        jTextAPELLIDO2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAPELLIDO2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAPELLIDO2FocusLost(evt);
            }
        });
        jTextAPELLIDO2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAPELLIDO2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPDATOSLayout = new javax.swing.GroupLayout(jPDATOS);
        jPDATOS.setLayout(jPDATOSLayout);
        jPDATOSLayout.setHorizontalGroup(
            jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPDATOSLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPDATOSLayout.createSequentialGroup()
                            .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextAPELLIDO)
                                .addComponent(jSepAPELLIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                            .addGap(50, 50, 50)
                            .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSepAPELLIDO2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextAPELLIDO2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPDATOSLayout.createSequentialGroup()
                            .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextNOMBRE)
                                .addComponent(jSepNOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                            .addGap(50, 50, 50)
                            .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSepNOMBRE1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextNOMBRE1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        jPDATOSLayout.setVerticalGroup(
            jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPDATOSLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNOMBRE1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSepNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSepNOMBRE1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAPELLIDO2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPDATOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSepAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSepAPELLIDO2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPPage1.add(jPDATOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 530, 120));

        jTextDNI.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jTextDNI.setForeground(new java.awt.Color(0, 153, 204));
        jTextDNI.setText("DNI");
        jTextDNI.setBorder(null);
        jTextDNI.setOpaque(false);
        jTextDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDNIFocusLost(evt);
            }
        });
        jTextDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDNIKeyTyped(evt);
            }
        });
        jPPage1.add(jTextDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 210, 30));
        jPPage1.add(jSepDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 210, 10));

        jSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "sexo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jSexo.setForeground(new java.awt.Color(0, 153, 204));
        jSexo.setOpaque(false);

        jPanelFenm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelFenm.setMaximumSize(new java.awt.Dimension(70, 70));
        jPanelFenm.setMinimumSize(new java.awt.Dimension(70, 70));
        jPanelFenm.setOpaque(false);
        jPanelFenm.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanelFenm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(244, 244, 244));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(0, 204, 204));
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_woman_70px.png"))); // NOI18N
        jRadioButton1.setMaximumSize(new java.awt.Dimension(70, 70));
        jRadioButton1.setMinimumSize(new java.awt.Dimension(70, 70));
        jRadioButton1.setOpaque(false);
        jRadioButton1.setPreferredSize(new java.awt.Dimension(70, 70));
        jRadioButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_woman_70px.png"))); // NOI18N
        jRadioButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseMoved(evt);
            }
        });
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseExited(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanelFenm.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelMan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelMan.setMaximumSize(new java.awt.Dimension(70, 70));
        jPanelMan.setMinimumSize(new java.awt.Dimension(70, 70));
        jPanelMan.setOpaque(false);
        jPanelMan.setPreferredSize(new java.awt.Dimension(70, 70));
        jPanelMan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton2.setBackground(new java.awt.Color(244, 244, 244));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setAlignmentY(0.0F);
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_standing_man_70px.png"))); // NOI18N
        jRadioButton2.setMaximumSize(new java.awt.Dimension(70, 70));
        jRadioButton2.setMinimumSize(new java.awt.Dimension(70, 70));
        jRadioButton2.setOpaque(false);
        jRadioButton2.setPreferredSize(new java.awt.Dimension(70, 70));
        jRadioButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_man_70px.png"))); // NOI18N
        jRadioButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseMoved(evt);
            }
        });
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseExited(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanelMan.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jSexoLayout = new javax.swing.GroupLayout(jSexo);
        jSexo.setLayout(jSexoLayout);
        jSexoLayout.setHorizontalGroup(
            jSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSexoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFenm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jSexoLayout.setVerticalGroup(
            jSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSexoLayout.createSequentialGroup()
                .addGroup(jSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFenm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPage1.add(jSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 180, 110));

        jPanelLocal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "localización", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelLocal.setOpaque(false);

        jPaisDeOrigen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAIS DE ORIGEN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jPaisDeOrigen.setOpaque(false);

        jComboPais.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboPais.setForeground(new java.awt.Color(0, 153, 204));
        jComboPais.setBorder(null);

        javax.swing.GroupLayout jPaisDeOrigenLayout = new javax.swing.GroupLayout(jPaisDeOrigen);
        jPaisDeOrigen.setLayout(jPaisDeOrigenLayout);
        jPaisDeOrigenLayout.setHorizontalGroup(
            jPaisDeOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaisDeOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboPais, 0, 226, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaisDeOrigenLayout.setVerticalGroup(
            jPaisDeOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaisDeOrigenLayout.createSequentialGroup()
                .addComponent(jComboPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jResidencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESIDENCIA ACTUAL", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 153, 204))); // NOI18N
        jResidencia.setOpaque(false);

        jComboResidencia.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboResidencia.setForeground(new java.awt.Color(0, 153, 204));
        jComboResidencia.setBorder(null);
        jComboResidencia.setOpaque(false);

        javax.swing.GroupLayout jResidenciaLayout = new javax.swing.GroupLayout(jResidencia);
        jResidencia.setLayout(jResidenciaLayout);
        jResidenciaLayout.setHorizontalGroup(
            jResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboResidencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jResidenciaLayout.setVerticalGroup(
            jResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResidenciaLayout.createSequentialGroup()
                .addComponent(jComboResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLocalLayout = new javax.swing.GroupLayout(jPanelLocal);
        jPanelLocal.setLayout(jPanelLocalLayout);
        jPanelLocalLayout.setHorizontalGroup(
            jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaisDeOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResidencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLocalLayout.setVerticalGroup(
            jPanelLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocalLayout.createSequentialGroup()
                .addComponent(jPaisDeOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPPage1.add(jPanelLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 290, 190));

        jPanelContacto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "datos de contacto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelContacto.setOpaque(false);

        jTextTelefono.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jTextTelefono.setForeground(new java.awt.Color(0, 153, 204));
        jTextTelefono.setText("TELÉFONO");
        jTextTelefono.setBorder(null);
        jTextTelefono.setOpaque(false);
        jTextTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTelefonoFocusLost(evt);
            }
        });
        jTextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefonoKeyTyped(evt);
            }
        });

        jTextCorreo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextCorreo.setForeground(new java.awt.Color(0, 153, 204));
        jTextCorreo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCorreo.setText("CORREO");
        jTextCorreo.setBorder(null);
        jTextCorreo.setOpaque(false);
        jTextCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextCorreoFocusLost(evt);
            }
        });
        jTextCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCorreoKeyTyped(evt);
            }
        });

        jComboBoxCorreo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jComboBoxCorreo.setForeground(new java.awt.Color(0, 153, 240));
        jComboBoxCorreo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@yahoo.com", "@myspace.com" }));
        jComboBoxCorreo.setBorder(null);

        javax.swing.GroupLayout jPanelContactoLayout = new javax.swing.GroupLayout(jPanelContacto);
        jPanelContacto.setLayout(jPanelContactoLayout);
        jPanelContactoLayout.setHorizontalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextTelefono)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContactoLayout.createSequentialGroup()
                        .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSepCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSepTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContactoLayout.createSequentialGroup()
                                .addComponent(jTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCorreo, 0, 125, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanelContactoLayout.setVerticalGroup(
            jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSepTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSepCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPage1.add(jPanelContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 340, 140));

        jCancel.setBackground(new java.awt.Color(0, 51, 51));
        jCancel.setForeground(new java.awt.Color(0, 51, 51));
        jCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px.png"))); // NOI18N
        jCancel.setBorder(null);
        jCancel.setBorderPainted(false);
        jCancel.setContentAreaFilled(false);
        jCancel.setPreferredSize(new java.awt.Dimension(40, 40));
        jCancel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_unavailable_80px_1.png"))); // NOI18N
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jPPage1.add(jCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 60, 60));

        jNext.setBackground(new java.awt.Color(0, 51, 51));
        jNext.setForeground(new java.awt.Color(0, 51, 51));
        jNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_2.png"))); // NOI18N
        jNext.setBorder(null);
        jNext.setBorderPainted(false);
        jNext.setContentAreaFilled(false);
        jNext.setPreferredSize(new java.awt.Dimension(40, 40));
        jNext.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_3.png"))); // NOI18N
        jNext.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_3.png"))); // NOI18N
        jNext.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_next_page_80px_3.png"))); // NOI18N
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        jPPage1.add(jNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 60, 60));

        jPanelEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "edad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanelEdad.setOpaque(false);

        jComboEdad.setFont(new java.awt.Font("Berlin Sans FB", 1, 20)); // NOI18N
        jComboEdad.setForeground(new java.awt.Color(0, 153, 204));
        jComboEdad.setBorder(null);
        jComboEdad.setOpaque(false);

        javax.swing.GroupLayout jPanelEdadLayout = new javax.swing.GroupLayout(jPanelEdad);
        jPanelEdad.setLayout(jPanelEdadLayout);
        jPanelEdadLayout.setHorizontalGroup(
            jPanelEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelEdadLayout.setVerticalGroup(
            jPanelEdadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEdadLayout.createSequentialGroup()
                .addComponent(jComboEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPPage1.add(jPanelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 120, 70));

        jPIngreso.add(jPPage1);
        jPPage1.setBounds(0, 0, 950, 670);

        jBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg1.gif"))); // NOI18N
        jBackGround.setMaximumSize(new java.awt.Dimension(950, 650));
        jBackGround.setMinimumSize(new java.awt.Dimension(950, 650));
        jBackGround.setPreferredSize(new java.awt.Dimension(950, 700));
        jPIngreso.add(jBackGround);
        jBackGround.setBounds(0, 0, 950, 670);

        getContentPane().add(jPIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 950, 670));

        jPanelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(950, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_minimize_window_30px_2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(894, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 950, 30));

        jPanelLateral.setBackground(new java.awt.Color(0, 51, 51));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(50, 700));

        jButtonClose.setBackground(new java.awt.Color(0, 51, 51));
        jButtonClose.setForeground(new java.awt.Color(0, 51, 51));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px.png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px_1.png"))); // NOI18N
        jButtonClose.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px_1.png"))); // NOI18N
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_70px_1.png"))); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralLayout = new javax.swing.GroupLayout(jPanelLateral);
        jPanelLateral.setLayout(jPanelLateralLayout);
        jPanelLateralLayout.setHorizontalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLateralLayout.setVerticalGroup(
            jPanelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralLayout.createSequentialGroup()
                .addContainerGap(609, Short.MAX_VALUE)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNOMBRE1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNOMBRE1FocusGained
         if(jTextNOMBRE1.getText().equals("NOMBRE (SEGUNDO)"))
            jTextNOMBRE1.setText("");
    }//GEN-LAST:event_jTextNOMBRE1FocusGained

    private void jTextAPELLIDOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAPELLIDOFocusGained
        if(jTextAPELLIDO.getText().equals("APELLIDO"))
            jTextAPELLIDO.setText("");
    }//GEN-LAST:event_jTextAPELLIDOFocusGained

    private void jTextAPELLIDO2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAPELLIDO2FocusGained
        if(jTextAPELLIDO2.getText().equals("APELLIDO (SEGUNDO)"))
            jTextAPELLIDO2.setText("");
    }//GEN-LAST:event_jTextAPELLIDO2FocusGained

    private void jTextDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusGained
        if(jTextDNI.getText().equals("DNI"))
            jTextDNI.setText("");
    }//GEN-LAST:event_jTextDNIFocusGained

    private void jTextTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTelefonoFocusGained
       if(jTextTelefono.getText().equals("TELÉFONO"))
            jTextTelefono.setText("");
    }//GEN-LAST:event_jTextTelefonoFocusGained

    private void jTextCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCorreoFocusGained
        if(jTextCorreo.getText().equals("CORREO"))
            jTextCorreo.setText("");
    }//GEN-LAST:event_jTextCorreoFocusGained

    private void jTextNOMBREFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNOMBREFocusLost
        if(jTextNOMBRE.getText().equals("")) 
           jTextNOMBRE.setText("NOMBRE");
    }//GEN-LAST:event_jTextNOMBREFocusLost

    private void jTextNOMBREFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNOMBREFocusGained
        if(jTextNOMBRE.getText().equals("NOMBRE"))
            jTextNOMBRE.setText("");        
    }//GEN-LAST:event_jTextNOMBREFocusGained

    private void jTextAPELLIDOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAPELLIDOFocusLost
        if(jTextAPELLIDO.getText().equals("")) 
            jTextAPELLIDO.setText("APELLIDO");
    }//GEN-LAST:event_jTextAPELLIDOFocusLost

    private void jTextNOMBRE1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNOMBRE1FocusLost
        if(jTextNOMBRE1.getText().equals("")) 
            jTextNOMBRE1.setText("NOMBRE (SEGUNDO)");
    }//GEN-LAST:event_jTextNOMBRE1FocusLost

    private void jTextAPELLIDO2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAPELLIDO2FocusLost
        if(jTextAPELLIDO2.getText().equals("")) 
            jTextAPELLIDO2.setText("APELLIDO (SEGUNDO)");
    }//GEN-LAST:event_jTextAPELLIDO2FocusLost

    private void jTextDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDNIFocusLost
        if(jTextDNI.getText().equals("")) 
            jTextDNI.setText("DNI");
    }//GEN-LAST:event_jTextDNIFocusLost

    private void jTextTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTelefonoFocusLost
        if(jTextTelefono.getText().equals("")) 
            jTextTelefono.setText("TELÉFONO");
    }//GEN-LAST:event_jTextTelefonoFocusLost

    private void jTextCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCorreoFocusLost
        if(jTextCorreo.getText().equals("")) 
            jTextCorreo.setText("CORREO");
    }//GEN-LAST:event_jTextCorreoFocusLost

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:  
        Dialogs d = new Dialogs(2);
        d.setVisible(true);
    
        if(d.getState() == true)
        {   mp = new Menu_Principal(connection);
            mp.setVisible(true);
	    dispose();
        }
    }//GEN-LAST:event_jCancelActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
                Dialogs d;
                if(campos_vacios()|| campos_iniciales())
                {
                 d = new Dialogs(6); //FORMULARIO INCOMPLETO
                 d.setVisible(true);
                }
                else {
				nuevo_postulante.setNombres(jTextNOMBRE.getText(), jTextNOMBRE1.getText());
				nuevo_postulante.setApellidos(jTextAPELLIDO.getText(), jTextAPELLIDO2.getText());
                                nuevo_postulante.setDNI(Integer.parseInt(jTextDNI.getText()));
				nuevo_postulante.setEdad(Integer.parseInt(jComboEdad.getSelectedItem().toString()));
				nuevo_postulante.setPais_origen(jComboPais.getSelectedItem().toString());
				nuevo_postulante.setResidencia(jComboResidencia.getSelectedItem().toString());
				nuevo_postulante.setTelefono(jTextTelefono.getText());
				nuevo_postulante.setCorreo(jTextCorreo.getText()+jComboBoxCorreo.getSelectedItem());
                                
                                // Agregando nuevo postulante a la base de datos.
                                if(agregarPostulanteDatabase()){
                                    //ABRIR SIGUIENTE PANTALLA
                                    fpc = new Formulario_Postulante_Conocimientos(nuevo_postulante, connection);
                                    fpc.setVisible(true);
                                    dispose();
                                }
			}   
    }//GEN-LAST:event_jNextActionPerformed

    //Seleccionar femenino
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        nuevo_postulante.setSexo("Femenino");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    //Seleccionar masculino
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        nuevo_postulante.setSexo("Masculino");
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    // Metodo de evento para establecer una limitacion de los caracteres que seran introducidos en los campos de texto (Numeros o Letras).
    private void jTextNOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNOMBREKeyTyped
        
        int character = (int)evt.getKeyChar();
        
        if(character < 65 || (character > 90 && character < 97) || character > 122 || (jTextNOMBRE.getText().length() + 1 > 20)){
            evt.consume();
            return;
        }
        
        char c=evt.getKeyChar();
            String s="";
            
                if(evt.getSource().equals(jTextNOMBRE)) {
                    if(Character.isDigit(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextNOMBRE.getText();
                        jTextNOMBRE.setText(null);
                        jTextNOMBRE.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextNOMBREKeyTyped

    private void jTextNOMBRE1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNOMBRE1KeyTyped
         
        int character = (int)evt.getKeyChar();
        
        if(character < 65 || (character > 90 && character < 97) || character > 122 || (jTextNOMBRE1.getText().length() + 1 > 20)){
            evt.consume();
            return;
        }
        
          char c=evt.getKeyChar();
            String s="";
            
               if(evt.getSource().equals(jTextNOMBRE1)) {
                    if(Character.isDigit(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextNOMBRE1.getText();
                        jTextNOMBRE1.setText(null);
                        jTextNOMBRE1.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextNOMBRE1KeyTyped

    private void jTextAPELLIDOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAPELLIDOKeyTyped
        
        int character = (int)evt.getKeyChar();
        
        if(character < 65 || (character > 90 && character < 97) || character > 122 || (jTextAPELLIDO.getText().length() + 1 > 20) ){
            evt.consume();
            return;
        }
        
        char c=evt.getKeyChar();
            String s="";
             
                if(evt.getSource().equals(jTextAPELLIDO)) {
                    if(Character.isDigit(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextAPELLIDO.getText();
                        jTextAPELLIDO.setText(null);
                        jTextAPELLIDO.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextAPELLIDOKeyTyped

    private void jTextAPELLIDO2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAPELLIDO2KeyTyped
        
        int character = (int)evt.getKeyChar();
        
        if(character < 65 || (character > 90 && character < 97) || character > 122 || (jTextAPELLIDO2.getText().length() + 1 > 20) ){
            evt.consume();
            return;
        }
        
          char c=evt.getKeyChar();
          String s="";            
           
                if(evt.getSource().equals(jTextAPELLIDO2)) {
                    if(Character.isDigit(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextAPELLIDO2.getText();
                        jTextAPELLIDO2.setText(null);
                        jTextAPELLIDO2.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextAPELLIDO2KeyTyped

    private void jTextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefonoKeyTyped
         
         int character = (int)evt.getKeyChar();
         
         if(character < 48 || character > 57 || (jTextTelefono.getText().length() + 1 > 15)){
             evt.consume();
             return;
         }
        
            char c=evt.getKeyChar();
            String s="";
             
                if(evt.getSource().equals(jTextTelefono)) {
                    if(Character.isLetter(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextTelefono.getText();
                        jTextTelefono.setText(null);
                        jTextTelefono.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextTelefonoKeyTyped

    private void jTextDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDNIKeyTyped
         
        int character = (int)evt.getKeyChar();
         
         if(character < 48 || character > 57 || (jTextDNI.getText().length() + 1 > 15)){
             evt.consume();
             return;
         }
        
        char c=evt.getKeyChar();
            String s="";
                             
                if(evt.getSource().equals(jTextDNI)){
                     if(Character.isLetter(c)||Character.isWhitespace(c)) {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextDNI.getText();
                        jTextDNI.setText(null);
                        jTextDNI.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextDNIKeyTyped

    private void jTextCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCorreoKeyTyped
       
         if(jTextCorreo.getText().length() + 1 > 40)
            evt.consume();
        
        char c = evt.getKeyChar(); 
            String s="";
               //|| || Character.isDigit(1)
                if(evt.getSource().equals(jTextCorreo)) {
                    if(Character.isWhitespace(c)  || c == '@'|| c == '-'|| c == '*'|| c == '/') {
                        getToolkit().beep(); 
                        evt.consume();
                        s=jTextCorreo.getText();
                        jTextCorreo.setText(null);
                        jTextCorreo.setText(s);
                    }
                }
    }//GEN-LAST:event_jTextCorreoKeyTyped

    private void jPPage1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPPage1MouseMoved
         
    }//GEN-LAST:event_jPPage1MouseMoved

    private void jRadioButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseExited
        jPanelFenm.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jRadioButton1MouseExited

    private void jRadioButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseMoved
        jPanelMan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jRadioButton2MouseMoved

    private void jRadioButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseExited
         jPanelMan.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_jRadioButton2MouseExited

    private void jRadioButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseMoved
        jPanelFenm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,204)));
    }//GEN-LAST:event_jRadioButton1MouseMoved

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        Dialogs d = new Dialogs(1);
        d.setVisible(true);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setState(Formulario_Postulante_Info_Personal.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void carga_edades() {
          for(int counter = 18; counter <= 60; counter++)
		jComboEdad.addItem(counter);
	}
    
     // Metodo para agregar un postulante a la base de datos.
    public boolean agregarPostulanteDatabase(){
            Dialogs d;
        
            try {
                PreparedStatement ps = connection.prepareStatement("INSERT INTO `postulantes` (`idpostulante`, `primernombre`, `segundonombre`, `primerapellido`, `segundoapellido`, `dni`, `edad`, `sexo`, `pais_origen`, `residencia`, `telefono`, `correo`) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                
                ps.setString(1, nuevo_postulante.getPrimerNombre());
                ps.setString(2, nuevo_postulante.getSegundoNombre());
                ps.setString(3, nuevo_postulante.getPrimerApellido());
                ps.setString(4, nuevo_postulante.getSegundoApellido());
                ps.setInt(5, nuevo_postulante.getDNI());
                ps.setInt(6, nuevo_postulante.getEdad());
                ps.setString(7, nuevo_postulante.getSexo());
                ps.setString(8, nuevo_postulante.getPais_origen());
                ps.setString(9, nuevo_postulante.getResidencia());
                ps.setString(10, nuevo_postulante.getTelefono());
                ps.setString(11, nuevo_postulante.getCorreo());
                
                // Verificamos si el DNI introducido o el correo ya se encuentran registrados.
                ResultSet rs = connection.prepareStatement("SELECT * FROM postulantes").executeQuery();
                
                while(rs.next())
                    if(rs.getInt(6) == nuevo_postulante.getDNI() || rs.getString(12).equalsIgnoreCase(nuevo_postulante.getCorreo())){
                        d = new Dialogs(3);//Ya Registrado
                        d.setVisible(true);
                        return false;
                    }
                
                ps.executeUpdate();
                d = new Dialogs(4);//CORRECTO
                d.setVisible(true);
                
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
                d = new Dialogs(5);
                d.setVisible(true);//ERROR GENERAL
            }
            
        return true;
    }

    //Método para cargar paises de la BBD al combobox
    private void cargarPaises(){
                
            try{
                ResultSet rs = connection.prepareStatement("SELECT * FROM paises").executeQuery();
                
                while(rs.next()){
                    jComboPais.addItem(rs.getString(3));
                    jComboResidencia.addItem(rs.getString(3));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Administracion_json.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            jComboPais.setSelectedIndex(231);
            jComboResidencia.setSelectedIndex(231);
        }
    
    //Verificación de espacios vacíos en TextFile
    private boolean campos_vacios() {
            if(jTextNOMBRE.getText().equals("")||jTextNOMBRE1.getText().equals("")||jTextAPELLIDO.getText().equals("")||jTextAPELLIDO2.getText().equals("")||jTextTelefono.getText().equals("")||jTextDNI.getText().equals("") || jTextCorreo.getText().equals(""))
		return true;
            return false;
	}
    
    //Verificación de cambio de valores iniciales de los TextFiles
    private boolean campos_iniciales() {
            if(jTextNOMBRE.getText().equals("NOMBRE")||jTextNOMBRE1.getText().equals("NOMBRE (SEGUNDO)")||jTextAPELLIDO.getText().equals("APELLIDO")||jTextAPELLIDO2.getText().equals("APELLIDO (SEGUNDO)")||jTextTelefono.getText().equals("TELÉFONO")||jTextCorreo.getText().equals("CORREO") || jTextDNI.getText().equals("DNI") || (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()))
		return true;
            return false;
    }
  
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PREVIOFormulario_Postulante_Conocimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PREVIOFormulario_Postulante_Conocimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PREVIOFormulario_Postulante_Conocimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PREVIOFormulario_Postulante_Conocimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PREVIOFormulario_Postulante_Conocimientos(connection).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jAvatar;
    private javax.swing.JLabel jBackGround;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jCancel;
    private javax.swing.JComboBox<String> jComboBoxCorreo;
    private javax.swing.JComboBox<Integer> jComboEdad;
    private javax.swing.JComboBox<String> jComboPais;
    private javax.swing.JComboBox<String> jComboResidencia;
    private javax.swing.JLabel jInfPersonal;
    private javax.swing.JButton jNext;
    private javax.swing.JPanel jPDATOS;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPPage1;
    private javax.swing.JPanel jPaisDeOrigen;
    private javax.swing.JPanel jPanelContacto;
    private javax.swing.JPanel jPanelEdad;
    private javax.swing.JPanel jPanelFenm;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelLocal;
    private javax.swing.JPanel jPanelMan;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel jResidencia;
    private javax.swing.JSeparator jSepAPELLIDO;
    private javax.swing.JSeparator jSepAPELLIDO2;
    private javax.swing.JSeparator jSepCorreo;
    private javax.swing.JSeparator jSepDNI;
    private javax.swing.JSeparator jSepNOMBRE;
    private javax.swing.JSeparator jSepNOMBRE1;
    private javax.swing.JSeparator jSepTelefono;
    private javax.swing.JPanel jSexo;
    private javax.swing.JTextField jTextAPELLIDO;
    private javax.swing.JTextField jTextAPELLIDO2;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextNOMBRE;
    private javax.swing.JTextField jTextNOMBRE1;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
