/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Jesus Gonzalez
 */
public class InfoDialogs extends javax.swing.JFrame {

    /**
     * Creates new form InfoDialogs
     */
    public InfoDialogs() {
        initComponents();
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    public InfoDialogs(int window){
        initComponents();        
        setFalseEverything();
               
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);    
    
        
        switch (window) {
            case 1:
                setPanelEnabled(jPanelInfoCV, true);
                jPanelInfoCV.setVisible(true);
                break;
            case 2:
                setPanelEnabled(jPanelInfoPerfil, true);
                jPanelInfoPerfil.setVisible(true);
                break;
            case 3:
                setPanelEnabled(jPanelInfoCandidatos, true);
                jPanelInfoCandidatos.setVisible(true);
                break;
                
            case 4:
                setPanelEnabled(jPanelInfoEvaluacion, true);
                jPanelInfoEvaluacion.setVisible(true);
                break;
            default: break;
        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoCV = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDescipcion = new javax.swing.JLabel();
        jPanelInfoPerfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDescipcion4 = new javax.swing.JLabel();
        jPanelInfoCandidatos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDescipcion5 = new javax.swing.JLabel();
        jPanelInfoEvaluacion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelDescipcion6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 236, 84));
        setFocusable(false);
        setFocusableWindowState(false);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfoCV.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoCV.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanelInfoCV.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanelInfoCV.setOpaque(false);
        jPanelInfoCV.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelInfoCV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dosis", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INGRESAR CV");
        jPanelInfoCV.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, -1));

        jLabelDescipcion.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabelDescipcion.setText("<html>Sección destinada al aspirante a un empleo.<br/>Aquí, ingresará su información personal seguida por sus conocimientos académicos como lo son su título, especialidad y herramientas manejadas<html>");
        jLabelDescipcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescipcion.setMaximumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion.setMinimumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion.setPreferredSize(new java.awt.Dimension(340, 160));
        jPanelInfoCV.add(jLabelDescipcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 160));

        getContentPane().add(jPanelInfoCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelInfoPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoPerfil.setAlignmentX(0.0F);
        jPanelInfoPerfil.setAlignmentY(0.0F);
        jPanelInfoPerfil.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanelInfoPerfil.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanelInfoPerfil.setOpaque(false);
        jPanelInfoPerfil.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelInfoPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dosis", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESAR PERFIL");
        jPanelInfoPerfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, -1));

        jLabelDescipcion4.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabelDescipcion4.setText("<html>Sección destinada a la empresa empleadora.<br/>Podrá registrar los requerimientos fundamentales para aspirar a un puesto de trabajo en dicha empresa. La oferta enmarcará la faceta del perfil para un proyecto, los detalles de las distintas herramientas y lenguajes profesionales más una breve descipción general.<html>");
        jLabelDescipcion4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescipcion4.setMaximumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion4.setMinimumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion4.setPreferredSize(new java.awt.Dimension(340, 160));
        jPanelInfoPerfil.add(jLabelDescipcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 160));

        getContentPane().add(jPanelInfoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelInfoCandidatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoCandidatos.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanelInfoCandidatos.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanelInfoCandidatos.setOpaque(false);
        jPanelInfoCandidatos.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelInfoCandidatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dosis", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CANDIDATOS");
        jPanelInfoCandidatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, -1));

        jLabelDescipcion5.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabelDescipcion5.setText("<html>Sección destinada a la empresa empleadora.<br/>Podrá consultar una lista de aquellos aspirantes seleccionados filtrados según una oferta específica y revisar su información de contacto<html>");
        jLabelDescipcion5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescipcion5.setMaximumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion5.setMinimumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion5.setPreferredSize(new java.awt.Dimension(340, 160));
        jPanelInfoCandidatos.add(jLabelDescipcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 160));

        getContentPane().add(jPanelInfoCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanelInfoEvaluacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoEvaluacion.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanelInfoEvaluacion.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanelInfoEvaluacion.setOpaque(false);
        jPanelInfoEvaluacion.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanelInfoEvaluacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dosis", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EVALUACIÓN");
        jPanelInfoEvaluacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, 360, 40));

        jLabelDescipcion6.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabelDescipcion6.setText("<html>El aspirante podrá consultar las ofertas disponibles y presentar una evaluación diagnóstica adaptable en nivel de dificultad que inicia con 10 preguntas de conocimientos generales, seguido de otras específicas según el perfil postulado.<br/> El índice de calificación se notificará al finalizar, quedando en consideración los aprobados para el empleo<html>");
        jLabelDescipcion6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelDescipcion6.setMaximumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion6.setMinimumSize(new java.awt.Dimension(340, 160));
        jLabelDescipcion6.setPreferredSize(new java.awt.Dimension(340, 160));
        jPanelInfoEvaluacion.add(jLabelDescipcion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 190));

        getContentPane().add(jPanelInfoEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_info_32px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bg5.png"))); // NOI18N
        jLabelBG.setAlignmentY(0.0F);
        jLabelBG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void setFalseEverything(){
       jPanelInfoCV.setVisible(false);
       jPanelInfoPerfil.setVisible(false);
       jPanelInfoCandidatos.setVisible(false);
       jPanelInfoEvaluacion.setVisible(false);    
    }
     
     private void setPanelEnabled(JPanel panel, Boolean isEnabled) {
    panel.setEnabled(isEnabled);

    Component[] components = panel.getComponents();

    for (Component component : components) {
        if (component instanceof JPanel) {
            setPanelEnabled((JPanel) component, isEnabled);
        }
        component.setEnabled(isEnabled);
    }
} 
    /**
     * @param args the command line arguments
     */
     
   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelDescipcion;
    private javax.swing.JLabel jLabelDescipcion4;
    private javax.swing.JLabel jLabelDescipcion5;
    private javax.swing.JLabel jLabelDescipcion6;
    private javax.swing.JPanel jPanelInfoCV;
    private javax.swing.JPanel jPanelInfoCandidatos;
    private javax.swing.JPanel jPanelInfoEvaluacion;
    private javax.swing.JPanel jPanelInfoPerfil;
    // End of variables declaration//GEN-END:variables
}
